// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheWatch.P12.Notifications;

#nullable disable

namespace TheWatch.P12.Notifications.Migrations
{
    [DbContext(typeof(NotificationsDbContext))]
    partial class NotificationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TheWatch.P12.Notifications.Notifications.BroadcastMessage", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                    b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<string>("Body").IsRequired().HasMaxLength(2000).HasColumnType("nvarchar(2000)");
                    b.Property<string>("Category").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<string>("Priority").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<string>("TargetArea").HasMaxLength(500).HasColumnType("nvarchar(500)");
                    b.Property<double?>("TargetLatitude").HasColumnType("float");
                    b.Property<double?>("TargetLongitude").HasColumnType("float");
                    b.Property<double?>("RadiusKm").HasColumnType("float");
                    b.Property<Guid>("SenderId").HasColumnType("uniqueidentifier");
                    b.Property<int>("RecipientsCount").HasColumnType("int");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("CreatedAt");
                    b.HasIndex("SenderId");
                    b.ToTable("BroadcastMessages");
                });

            modelBuilder.Entity("TheWatch.P12.Notifications.Notifications.NotificationPreference", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                    b.Property<Guid>("UserId").HasColumnType("uniqueidentifier");
                    b.Property<string>("Category").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<bool>("PushEnabled").HasColumnType("bit");
                    b.Property<bool>("SmsEnabled").HasColumnType("bit");
                    b.Property<bool>("EmailEnabled").HasColumnType("bit");
                    b.Property<bool>("InAppEnabled").HasColumnType("bit");
                    b.Property<string>("QuietHoursStart").HasMaxLength(10).HasColumnType("nvarchar(10)");
                    b.Property<string>("QuietHoursEnd").HasMaxLength(10).HasColumnType("nvarchar(10)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("UserId");
                    b.ToTable("NotificationPreferences");
                });

            modelBuilder.Entity("TheWatch.P12.Notifications.Notifications.NotificationRecord", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                    b.Property<Guid>("RecipientId").HasColumnType("uniqueidentifier");
                    b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<string>("Body").IsRequired().HasMaxLength(2000).HasColumnType("nvarchar(2000)");
                    b.Property<string>("Channel").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<string>("Priority").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<string>("Status").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<string>("Category").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<string>("DeepLink").HasMaxLength(2048).HasColumnType("nvarchar(2048)");
                    b.Property<string>("ImageUrl").HasMaxLength(2048).HasColumnType("nvarchar(2048)");
                    b.Property<string>("FcmMessageId").HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<string>("ErrorMessage").HasMaxLength(1000).HasColumnType("nvarchar(1000)");
                    b.Property<DateTime?>("SentAt").HasColumnType("datetime2");
                    b.Property<DateTime?>("DeliveredAt").HasColumnType("datetime2");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("Category");
                    b.HasIndex("CreatedAt");
                    b.HasIndex("RecipientId");
                    b.HasIndex("Status");
                    b.ToTable("NotificationRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
