// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheWatch.P6.FirstResponder;

#nullable disable

namespace TheWatch.P6.FirstResponder.Migrations
{
    [DbContext(typeof(FirstResponderDbContext))]
    [Migration("20260226110629_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TheWatch.P6.FirstResponder.Responders.CheckIn", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("ResponderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.HasIndex("ResponderId");

                    b.HasIndex("Type");

                    b.ToTable("CheckIns");
                });

            modelBuilder.Entity("TheWatch.P6.FirstResponder.Responders.Responder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BadgeNumber")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.PrimitiveCollection<string>("Certifications")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LocationUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("MaxResponseRadiusKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("LocationUpdatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("Responders");
                });

            modelBuilder.Entity("TheWatch.P6.FirstResponder.Responders.CheckIn", b =>
                {
                    b.OwnsOne("TheWatch.P6.FirstResponder.Responders.GeoLocation", "Location", b1 =>
                        {
                            b1.Property<Guid>("CheckInId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double?>("Accuracy")
                                .HasColumnType("float");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");

                            b1.Property<DateTime?>("Timestamp")
                                .HasColumnType("datetime2");

                            b1.HasKey("CheckInId");

                            b1.ToTable("CheckIns");

                            b1.WithOwner()
                                .HasForeignKey("CheckInId");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("TheWatch.P6.FirstResponder.Responders.Responder", b =>
                {
                    b.OwnsOne("TheWatch.P6.FirstResponder.Responders.GeoLocation", "LastKnownLocation", b1 =>
                        {
                            b1.Property<Guid>("ResponderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double?>("Accuracy")
                                .HasColumnType("float");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");

                            b1.Property<DateTime?>("Timestamp")
                                .HasColumnType("datetime2");

                            b1.HasKey("ResponderId");

                            b1.ToTable("Responders");

                            b1.WithOwner()
                                .HasForeignKey("ResponderId");
                        });

                    b.Navigation("LastKnownLocation");
                });
#pragma warning restore 612, 618
        }
    }
}
