using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace TheWatch.Generators;

[Generator]
public class HangfireJobGenerator : IIncrementalGenerator
{
    // Operations that should be async background jobs
    private static readonly HashSet<string> AsyncPatterns = new HashSet<string>(new[]
    {
        "upload", "process", "notify", "send", "dispatch", "expand", "escalate",
        "sync", "import", "export", "generate", "analyze", "scan", "warm",
        "cleanup", "archive", "backup", "batch", "bulk", "fan", "broadcast",
        "evacuate", "alert", "evidence", "audit", "log", "index", "cache"
    });

    // Recurring job patterns
    private static readonly HashSet<string> RecurringPatterns = new HashSet<string>(new[]
    {
        "health", "check", "monitor", "warm", "sync", "refresh", "cleanup",
        "expire", "heartbeat", "ping", "validate", "reconcile"
    });

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var mappingFiles = context.AdditionalTextsProvider
            .Where(f => f.Path.EndsWith("_mapping.json"));

        var projectName = context.AnalyzerConfigOptionsProvider
            .Select((opts, _) =>
            {
                opts.GlobalOptions.TryGetValue("build_property.RootNamespace", out var ns);
                return ns ?? "TheWatch";
            });

        var combined = mappingFiles.Collect().Combine(projectName);

        context.RegisterSourceOutput(combined, (spc, pair) =>
        {
            var (files, rootNs) = pair;
            if (files.IsEmpty) return;
            if (rootNs.Contains(".Tests")) return;

            var program = GeneratorHelpers.DetectProgram(rootNs);
            if (program == null) return;

            var text = files[0].GetText()?.ToString();
            if (text == null) return;

            var mapping = JsonDocument.Parse(text).RootElement;
            GenerateJobs(spc, mapping, program, rootNs);
        });
    }

    private static void GenerateJobs(SourceProductionContext ctx, JsonElement mapping,
        string program, string rootNs)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Hangfire;");
        sb.AppendLine("using Microsoft.Extensions.Logging;");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNs}.Jobs;");
        sb.AppendLine();

        var fireAndForget = new List<(string Name, string Summary)>();
        var recurring = new List<(string Name, string Summary)>();
        var emitted = new HashSet<string>();

        void ClassifyOperation(string opId, string method, string path, string summary)
        {
            var name = GeneratorHelpers.ExtractOperationName(opId, method, path);
            if (!emitted.Add(name)) return;

            var lower = name.ToLowerInvariant() + " " + summary.ToLowerInvariant();
            if (RecurringPatterns.Any(p => lower.Contains(p)))
                recurring.Add((name, summary));
            else if (AsyncPatterns.Any(p => lower.Contains(p)))
                fireAndForget.Add((name, summary));
        }

        // Scan all operations for this program
        if (mapping.TryGetProperty("controllerMatches", out var ctrlMatches))
        {
            foreach (var m in ctrlMatches.EnumerateArray())
            {
                if (m.GetProperty("program").GetString() != program) continue;
                ClassifyOperation(
                    m.GetProperty("operationId").GetString() ?? "",
                    m.GetProperty("httpMethod").GetString() ?? "GET",
                    m.GetProperty("operationPath").GetString() ?? "/",
                    m.GetProperty("operationSummary").GetString() ?? "");
            }
        }

        if (mapping.TryGetProperty("unmatchedOperations", out var unmatchedOps))
        {
            foreach (var op in unmatchedOps.EnumerateArray())
            {
                if (op.GetProperty("program").GetString() != program) continue;
                ClassifyOperation(
                    op.GetProperty("operationId").GetString() ?? "",
                    op.GetProperty("method").GetString() ?? "GET",
                    op.GetProperty("path").GetString() ?? "/",
                    op.GetProperty("summary").GetString() ?? "");
            }
        }

        // Emit fire-and-forget jobs
        foreach (var (name, summary) in fireAndForget)
        {
            EmitJobClass(sb, name, summary, "FireAndForget", rootNs);
        }

        // Emit recurring jobs
        foreach (var (name, summary) in recurring)
        {
            EmitJobClass(sb, name, summary, "Recurring", rootNs);
        }

        // Emit registration extension
        sb.AppendLine("public static class HangfireJobRegistrations");
        sb.AppendLine("{");
        sb.AppendLine("    public static void RegisterAllJobs(this IServiceCollection services)");
        sb.AppendLine("    {");
        foreach (var (name, _) in fireAndForget.Concat(recurring))
        {
            sb.AppendLine($"        services.AddTransient<{name}Job>();");
        }
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public static void ConfigureRecurringJobs()");
        sb.AppendLine("    {");
        foreach (var (name, _) in recurring)
        {
            sb.AppendLine($"        RecurringJob.AddOrUpdate<{name}Job>(\"{name}\", j => j.ExecuteAsync(), Cron.Minutely);");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource("HangfireJobs.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void EmitJobClass(StringBuilder sb, string name, string summary,
        string jobType, string rootNs)
    {
        if (!string.IsNullOrEmpty(summary))
            sb.AppendLine($"/// <summary>{summary} [{jobType}]</summary>");

        sb.AppendLine($"public class {name}Job");
        sb.AppendLine("{");
        sb.AppendLine($"    private readonly ILogger<{name}Job> _logger;");
        sb.AppendLine();
        sb.AppendLine($"    public {name}Job(ILogger<{name}Job> logger)");
        sb.AppendLine("    {");
        sb.AppendLine("        _logger = logger;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    [AutomaticRetry(Attempts = 3)]");
        sb.AppendLine("    public async Task ExecuteAsync()");
        sb.AppendLine("    {");
        sb.AppendLine($"        _logger.LogInformation(\"Starting {name} job\");");
        sb.AppendLine("        await Task.CompletedTask;");
        sb.AppendLine("        throw new NotImplementedException();");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
    }
}
