using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace TheWatch.Generators;

[Generator]
public class KafkaEventBusGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var projectInfo = context.AnalyzerConfigOptionsProvider
            .Select((opts, _) =>
            {
                opts.GlobalOptions.TryGetValue("build_property.RootNamespace", out var ns);
                opts.GlobalOptions.TryGetValue("build_property.UseMaui", out var useMaui);
                return new ProjectMeta(ns ?? "TheWatch", useMaui ?? "");
            });

        context.RegisterSourceOutput(projectInfo, static (spc, info) =>
        {
            var rootNs = info.Namespace;
            if (rootNs.Contains(".Tests") || rootNs.Contains(".Generators") ||
                rootNs.Contains(".Shared") || rootNs.Contains(".AppHost") ||
                rootNs.Contains(".ServiceDefaults") || rootNs.Contains(".Dashboard"))
                return;
            if (info.UseMaui.Equals("true", StringComparison.OrdinalIgnoreCase) ||
                rootNs.Contains(".Mobile"))
                return;

            var program = GeneratorHelpers.DetectProgram(rootNs);
            if (program == null) return;

            var parts = rootNs.Split('.');
            var shortName = parts.Length >= 3 ? parts[parts.Length - 1] : program;

            EmitKafkaSetup(spc, rootNs, shortName, program);
        });
    }

    private static void EmitKafkaSetup(SourceProductionContext ctx, string rootNs,
        string shortName, string program)
    {
        var sb = new StringBuilder(4096);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Kafka event bus setup generated by TheWatch.Generators.KafkaEventBusGenerator");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using Confluent.Kafka;");
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.Extensions.Configuration;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.Hosting;");
        sb.AppendLine("using Microsoft.Extensions.Logging;");
        sb.AppendLine("using TheWatch.Shared.Events;");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNs};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Auto-generated Kafka event bus setup for {rootNs}.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class KafkaSetup");
        sb.AppendLine("{");
        sb.AppendLine($"    public const string ServiceName = \"{rootNs}\";");
        sb.AppendLine($"    public const string ConsumerGroup = \"watch-{shortName.ToLowerInvariant()}\";");
        sb.AppendLine();

        // AddWatchKafka — registers producer, DLQ handler, audit logger, publisher
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers Kafka producer, event publisher, dead letter handler, and audit logger.");
        sb.AppendLine("    /// Call from Program.cs: builder.AddWatchKafka();");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static WebApplicationBuilder AddWatchKafka(this WebApplicationBuilder builder)");
        sb.AppendLine("    {");
        sb.AppendLine("        var bootstrapServers = builder.Configuration.GetConnectionString(\"kafka\")");
        sb.AppendLine("            ?? builder.Configuration[\"Kafka:BootstrapServers\"]");
        sb.AppendLine("            ?? \"localhost:9092\";");
        sb.AppendLine();
        sb.AppendLine("        // Producer (shared singleton)");
        sb.AppendLine("        builder.Services.AddSingleton<IProducer<string, string>>(sp =>");
        sb.AppendLine("        {");
        sb.AppendLine("            var config = new ProducerConfig");
        sb.AppendLine("            {");
        sb.AppendLine("                BootstrapServers = bootstrapServers,");
        sb.AppendLine($"                ClientId = \"{shortName.ToLowerInvariant()}-producer\",");
        sb.AppendLine("                Acks = Acks.All,");
        sb.AppendLine("                EnableIdempotence = true,");
        sb.AppendLine("                MessageSendMaxRetries = 3,");
        sb.AppendLine("                RetryBackoffMs = 100");
        sb.AppendLine("            };");
        sb.AppendLine("            return new ProducerBuilder<string, string>(config).Build();");
        sb.AppendLine("        });");
        sb.AppendLine();
        sb.AppendLine("        // Audit logger");
        sb.AppendLine("        builder.Services.AddSingleton<IEventAuditLogger, SerilogEventAuditLogger>();");
        sb.AppendLine();
        sb.AppendLine("        // Dead letter handler");
        sb.AppendLine("        builder.Services.AddSingleton<IDeadLetterHandler>(sp =>");
        sb.AppendLine("        {");
        sb.AppendLine("            var producer = sp.GetRequiredService<IProducer<string, string>>();");
        sb.AppendLine("            var logger = sp.GetRequiredService<ILogger<KafkaDeadLetterHandler>>();");
        sb.AppendLine("            return new KafkaDeadLetterHandler(producer, logger);");
        sb.AppendLine("        });");
        sb.AppendLine();
        sb.AppendLine("        // Event publisher");
        sb.AppendLine("        builder.Services.AddSingleton<IEventPublisher>(sp =>");
        sb.AppendLine("        {");
        sb.AppendLine("            var producer = sp.GetRequiredService<IProducer<string, string>>();");
        sb.AppendLine("            var audit = sp.GetRequiredService<IEventAuditLogger>();");
        sb.AppendLine("            var logger = sp.GetRequiredService<ILogger<KafkaEventPublisher>>();");
        sb.AppendLine("            return new KafkaEventPublisher(producer, audit, logger, ServiceName);");
        sb.AppendLine("        });");
        sb.AppendLine();
        sb.AppendLine("        return builder;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // AddWatchKafkaConsumer<T> — helper to register a consumer hosted service
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers a Kafka event consumer as a hosted background service.");
        sb.AppendLine("    /// Usage: builder.AddWatchKafkaConsumer&lt;MyConsumer&gt;();");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static WebApplicationBuilder AddWatchKafkaConsumer<TConsumer>(");
        sb.AppendLine("        this WebApplicationBuilder builder)");
        sb.AppendLine("        where TConsumer : class, IHostedService");
        sb.AppendLine("    {");
        sb.AppendLine("        builder.Services.AddHostedService<TConsumer>();");
        sb.AppendLine("        return builder;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // CreateConsumer — helper to build a Kafka consumer with standard config
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Creates a Kafka consumer with standard configuration for this service.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IConsumer<string, string> CreateConsumer(");
        sb.AppendLine("        IConfiguration configuration, string? groupOverride = null)");
        sb.AppendLine("    {");
        sb.AppendLine("        var bootstrapServers = configuration.GetConnectionString(\"kafka\")");
        sb.AppendLine("            ?? configuration[\"Kafka:BootstrapServers\"]");
        sb.AppendLine("            ?? \"localhost:9092\";");
        sb.AppendLine();
        sb.AppendLine("        var config = new ConsumerConfig");
        sb.AppendLine("        {");
        sb.AppendLine("            BootstrapServers = bootstrapServers,");
        sb.AppendLine("            GroupId = groupOverride ?? ConsumerGroup,");
        sb.AppendLine("            AutoOffsetReset = AutoOffsetReset.Earliest,");
        sb.AppendLine("            EnableAutoCommit = false,");
        sb.AppendLine("            EnableAutoOffsetStore = false");
        sb.AppendLine("        };");
        sb.AppendLine("        return new ConsumerBuilder<string, string>(config).Build();");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        ctx.AddSource("KafkaSetup.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private struct ProjectMeta : IEquatable<ProjectMeta>
    {
        public string Namespace;
        public string UseMaui;
        public ProjectMeta(string ns, string useMaui) { Namespace = ns; UseMaui = useMaui; }
        public bool Equals(ProjectMeta other) => Namespace == other.Namespace && UseMaui == other.UseMaui;
        public override bool Equals(object obj) => obj is ProjectMeta o && Equals(o);
        public override int GetHashCode() => (Namespace?.GetHashCode() ?? 0) ^ (UseMaui?.GetHashCode() ?? 0);
    }
}
