using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace TheWatch.Generators;

[Generator]
public class ModelGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var modelFiles = context.AdditionalTextsProvider
            .Where(f => f.Path.EndsWith("Models.json"));

        var mappingFiles = context.AdditionalTextsProvider
            .Where(f => f.Path.EndsWith("_mapping.json"));

        var projectName = context.AnalyzerConfigOptionsProvider
            .Select((opts, _) =>
            {
                opts.GlobalOptions.TryGetValue("build_property.RootNamespace", out var ns);
                return ns ?? "TheWatch";
            });

        var combined = modelFiles.Collect()
            .Combine(mappingFiles.Collect())
            .Combine(projectName);

        context.RegisterSourceOutput(combined, (spc, pair) =>
        {
            var ((modelTexts, mappingTexts), rootNs) = pair;
            if (modelTexts.IsEmpty) return;

            if (rootNs.Contains(".Tests")) return;

            var program = GeneratorHelpers.DetectProgram(rootNs);
            if (program == null) return;

            var modelsJson = modelTexts[0].GetText()?.ToString();
            if (modelsJson == null) return;

            var models = JsonDocument.Parse(modelsJson).RootElement;

            // Load mapping to know which models belong to this program
            HashSet<string>? programModels = null;
            if (!mappingTexts.IsEmpty)
            {
                var mappingText = mappingTexts[0].GetText()?.ToString();
                if (mappingText != null)
                {
                    var mapping = JsonDocument.Parse(mappingText).RootElement;
                    programModels = new HashSet<string>();
                    if (mapping.TryGetProperty("modelMatches", out var matches))
                    {
                        foreach (var m in matches.EnumerateArray())
                        {
                            if (m.GetProperty("program").GetString() == program)
                                programModels.Add(m.GetProperty("model").GetString() ?? "");
                        }
                    }
                }
            }

            GenerateModels(spc, models, program, rootNs, programModels);

            // Also generate models from unmatched schemas
            if (!mappingTexts.IsEmpty)
            {
                var mappingText = mappingTexts[0].GetText()?.ToString();
                if (mappingText != null)
                {
                    var mapping = JsonDocument.Parse(mappingText).RootElement;
                    GenerateSchemaModels(spc, mapping, program, rootNs);
                }
            }
        });
    }

    private static void GenerateModels(SourceProductionContext ctx, JsonElement modelsDoc,
        string program, string rootNs, HashSet<string>? programModels)
    {
        if (!modelsDoc.TryGetProperty("entries", out var entries)) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.ComponentModel.DataAnnotations;");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNs}.Models;");
        sb.AppendLine();

        int count = 0;
        var emitted = new HashSet<string>();

        foreach (var entry in entries.EnumerateArray())
        {
            var name = entry.GetProperty("name").GetString() ?? "";
            if (string.IsNullOrEmpty(name)) continue;
            if (programModels != null && !programModels.Contains(name)) continue;
            var safeName = GeneratorHelpers.SanitizeIdentifier(name);
            if (!emitted.Add(safeName)) continue;

            var kind = entry.TryGetProperty("kind", out var k) ? k.GetString() : "class";
            var typeKeyword = kind == "record" ? "record" : kind == "struct" ? "struct" : "class";

            // Inheritance — skip base classes since they may not exist in this project
            var inherits = "";

            sb.AppendLine($"public {typeKeyword} {safeName}{inherits}");
            sb.AppendLine("{");

            var propNames = new HashSet<string>();
            if (entry.TryGetProperty("properties", out var props))
            {
                foreach (var prop in props.EnumerateArray())
                {
                    var propName = prop.TryGetProperty("name", out var pn) ? pn.GetString() : null;
                    if (string.IsNullOrEmpty(propName)) continue;
                    var rawType = prop.TryGetProperty("type", out var pt) ? pt.GetString() : "string";
                    var propType = GeneratorHelpers.CleanPropertyType(rawType ?? "string");

                    var safePropName = GeneratorHelpers.SanitizeIdentifier(propName!);
                    // Skip duplicate properties and properties named same as enclosing type
                    if (!propNames.Add(safePropName)) continue;
                    if (safePropName == safeName) safePropName = safePropName + "Value";

                    sb.AppendLine($"    public {propType} {safePropName} {{ get; set; }}");
                }
            }

            sb.AppendLine("}");
            sb.AppendLine();
            count++;
        }

        if (count > 0)
            ctx.AddSource("Models.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void GenerateSchemaModels(SourceProductionContext ctx, JsonElement mapping,
        string program, string rootNs)
    {
        if (!mapping.TryGetProperty("unmatchedSchemas", out var schemas)) return;

        var programSchemas = schemas.EnumerateArray()
            .Where(s => s.GetProperty("program").GetString() == program)
            .ToList();

        if (!programSchemas.Any()) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated from OpenAPI schemas with no existing model");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNs}.Models;");
        sb.AppendLine();

        var emitted = new HashSet<string>();

        foreach (var schema in programSchemas)
        {
            var name = schema.GetProperty("schemaName").GetString() ?? "";
            if (string.IsNullOrEmpty(name)) continue;
            var safeName = GeneratorHelpers.SanitizeIdentifier(name);
            if (!emitted.Add(safeName)) continue;

            sb.AppendLine($"public class {safeName}");
            sb.AppendLine("{");

            var schemaPropNames = new HashSet<string>();
            if (schema.TryGetProperty("properties", out var props))
            {
                foreach (var prop in props.EnumerateArray())
                {
                    var propName = prop.GetString();
                    if (string.IsNullOrEmpty(propName)) continue;
                    var safeProp = GeneratorHelpers.PascalCase(GeneratorHelpers.SanitizeIdentifier(propName));
                    if (!schemaPropNames.Add(safeProp)) continue;
                    if (safeProp == safeName) safeProp = safeProp + "Value";
                    sb.AppendLine($"    public object? {safeProp} {{ get; set; }}");
                }
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }

        ctx.AddSource("SchemaModels.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
