using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace TheWatch.Generators;

[Generator]
public class NotificationGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var projectInfo = context.AnalyzerConfigOptionsProvider
            .Select((opts, _) =>
            {
                opts.GlobalOptions.TryGetValue("build_property.RootNamespace", out var ns);
                opts.GlobalOptions.TryGetValue("build_property.UseMaui", out var useMaui);
                return (Namespace: ns ?? "TheWatch", UseMaui: useMaui ?? "");
            });

        context.RegisterSourceOutput(projectInfo, (spc, info) =>
        {
            var rootNs = info.Namespace;
            // Skip test projects, the generator itself, shared, MAUI, and non-service projects
            if (rootNs.Contains(".Tests") || rootNs.Contains(".Generators") ||
                rootNs.Contains(".Shared") || rootNs.Contains(".AppHost") ||
                rootNs.Contains(".ServiceDefaults") || rootNs.Contains(".Dashboard"))
                return;
            if (info.UseMaui.Equals("true", System.StringComparison.OrdinalIgnoreCase) ||
                rootNs.Contains(".Mobile"))
                return;

            var program = GeneratorHelpers.DetectProgram(rootNs);
            if (program == null) return;

            var shortName = ExtractShortName(rootNs, program);
            EmitNotificationSetup(spc, rootNs, shortName, program);
        });
    }

    private static string ExtractShortName(string rootNs, string program)
    {
        var parts = rootNs.Split('.');
        return parts.Length >= 3 ? parts[parts.Length - 1] : program;
    }

    private static void EmitNotificationSetup(SourceProductionContext ctx, string rootNs,
        string shortName, string program)
    {
        var channel = MapProgramToChannel(program);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Push notification configuration generated by TheWatch.Generators.NotificationGenerator");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using FirebaseAdmin;");
        sb.AppendLine("using Google.Apis.Auth.OAuth2;");
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.Extensions.Configuration;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.Logging;");
        sb.AppendLine("using TheWatch.Shared.Notifications;");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNs};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Auto-generated push notification configuration for {rootNs}.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class NotificationSetup");
        sb.AppendLine("{");
        sb.AppendLine($"    public const string ServiceName = \"{rootNs}\";");
        sb.AppendLine($"    public const string DefaultChannel = \"{channel}\";");
        sb.AppendLine($"    public const string DefaultTopic = \"watch-{shortName.ToLowerInvariant()}\";");
        sb.AppendLine();

        // ConfigureWatchNotifications extension
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers Firebase Cloud Messaging notification service.");
        sb.AppendLine("    /// Reads \"Firebase:CredentialPath\" from configuration.");
        sb.AppendLine("    /// Falls back to NoOpNotificationService when Firebase is not configured.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static WebApplicationBuilder ConfigureWatchNotifications(this WebApplicationBuilder builder)");
        sb.AppendLine("    {");
        sb.AppendLine("        var credPath = builder.Configuration[\"Firebase:CredentialPath\"];");
        sb.AppendLine();
        sb.AppendLine("        if (!string.IsNullOrEmpty(credPath) && System.IO.File.Exists(credPath))");
        sb.AppendLine("        {");
        sb.AppendLine("            // Initialize Firebase App (idempotent — safe to call multiple times)");
        sb.AppendLine("            if (FirebaseApp.DefaultInstance == null)");
        sb.AppendLine("            {");
        sb.AppendLine("                FirebaseApp.Create(new AppOptions");
        sb.AppendLine("                {");
        sb.AppendLine("                    Credential = GoogleCredential.FromFile(credPath)");
        sb.AppendLine("                });");
        sb.AppendLine("            }");
        sb.AppendLine("            builder.Services.AddSingleton<INotificationService, FirebaseNotificationService>();");
        sb.AppendLine("        }");
        sb.AppendLine("        else");
        sb.AppendLine("        {");
        sb.AppendLine("            // No Firebase credentials — use no-op for development");
        sb.AppendLine("            builder.Services.AddSingleton<INotificationService, NoOpNotificationService>();");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return builder;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Helper to create a notification pre-filled with service defaults
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Creates a NotificationMessage pre-filled with {shortName} defaults.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static NotificationMessage CreateNotification(");
        sb.AppendLine("        string title,");
        sb.AppendLine("        string body,");
        sb.AppendLine("        NotificationPriority priority = NotificationPriority.Normal,");
        sb.AppendLine("        Dictionary<string, string>? data = null)");
        sb.AppendLine("    {");
        sb.AppendLine("        return new NotificationMessage");
        sb.AppendLine("        {");
        sb.AppendLine("            Title = title,");
        sb.AppendLine("            Body = body,");
        sb.AppendLine($"            Channel = NotificationChannel.{channel},");
        sb.AppendLine("            Priority = priority,");
        sb.AppendLine($"            Data = data ?? new Dictionary<string, string> {{ [\"source\"] = \"{shortName}\" }}");
        sb.AppendLine("        };");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        ctx.AddSource("NotificationSetup.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string MapProgramToChannel(string program)
    {
        switch (program)
        {
            case "P2": return "Emergency";
            case "P6": return "Dispatch";
            case "P7": return "FamilyCheckIn";
            case "P8": return "DisasterAlert";
            case "P9": return "Appointment";
            case "P10": return "Gamification";
            default: return "System";
        }
    }
}
