using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace TheWatch.Generators;

[Generator]
public class RestApiControllerGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var controllersFile = context.AdditionalTextsProvider
            .Where(f => f.Path.EndsWith("Controllers.json"));

        var mappingFile = context.AdditionalTextsProvider
            .Where(f => f.Path.EndsWith("_mapping.json"));

        var projectName = context.AnalyzerConfigOptionsProvider
            .Select((opts, _) =>
            {
                opts.GlobalOptions.TryGetValue("build_property.RootNamespace", out var ns);
                return ns ?? "TheWatch";
            });

        var combined = controllersFile.Collect()
            .Combine(mappingFile.Collect())
            .Combine(projectName);

        context.RegisterSourceOutput(combined, (spc, pair) =>
        {
            var ((ctrlFiles, mapFiles), rootNs) = pair;

            // Skip non-service projects
            if (rootNs.Contains(".Tests") || rootNs.Contains(".Generators") ||
                rootNs.Contains(".Mobile") || rootNs.Contains("Dashboard") ||
                rootNs.Contains("Shared") || rootNs.Contains("ServiceDefaults") ||
                rootNs.Contains("AppHost"))
                return;

            var program = GeneratorHelpers.DetectProgram(rootNs);
            if (program == null) return;

            string controllersJson = null;
            string mappingJson = null;

            if (!ctrlFiles.IsEmpty)
                controllersJson = ctrlFiles[0].GetText()?.ToString();
            if (!mapFiles.IsEmpty)
                mappingJson = mapFiles[0].GetText()?.ToString();

            // We need at least the mapping file to know which controllers belong to this program
            if (mappingJson == null) return;

            var mappingDoc = JsonDocument.Parse(mappingJson);
            JsonDocument controllersDoc = null;
            if (controllersJson != null)
                controllersDoc = JsonDocument.Parse(controllersJson);

            GenerateControllers(spc, controllersDoc, mappingDoc, program, rootNs);
            GenerateDtos(spc, controllersDoc, mappingDoc, program, rootNs);
            GenerateSetup(spc, rootNs);
        });
    }

    private static void GenerateControllers(SourceProductionContext ctx,
        JsonDocument controllersDoc, JsonDocument mappingDoc, string program, string rootNs)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// REST API controllers generated by TheWatch.Generators.RestApiControllerGenerator");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.AspNetCore.Authorization;");
        sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
        sb.AppendLine("using Microsoft.Extensions.Logging;");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNs}.Controllers;");
        sb.AppendLine();

        int controllerCount = 0;

        // 1. Generate controllers from Controllers.json entries matched to this program
        var programControllerNames = GetProgramControllerNames(mappingDoc, program);
        if (controllersDoc != null && programControllerNames.Count > 0)
        {
            if (controllersDoc.RootElement.TryGetProperty("entries", out var entries))
            {
                foreach (var entry in entries.EnumerateArray())
                {
                    if (!entry.TryGetProperty("name", out var nameEl)) continue;
                    var name = nameEl.GetString() ?? "";
                    if (!programControllerNames.Contains(name)) continue;
                    // Only emit actual controllers (have methods and inherit ControllerBase)
                    if (!entry.TryGetProperty("methods", out var methods)) continue;
                    if (!HasControllerBase(entry)) continue;

                    EmitController(sb, entry, name, methods);
                    controllerCount++;
                }
            }
        }

        // 2. Generate synthetic controllers from unmatched operations grouped by tag
        var unmatchedControllers = GroupUnmatchedByTag(mappingDoc, program);
        foreach (var kvp in unmatchedControllers)
        {
            var controllerName = kvp.Key;
            // Skip if a real controller with this name was already emitted
            if (programControllerNames.Contains(controllerName)) continue;

            EmitSyntheticController(sb, controllerName, kvp.Value);
            controllerCount++;
        }

        if (controllerCount == 0) return;

        ctx.AddSource("RestApiControllers.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static HashSet<string> GetProgramControllerNames(JsonDocument mappingDoc, string program)
    {
        var names = new HashSet<string>();
        if (mappingDoc.RootElement.TryGetProperty("programSummary", out var summary) &&
            summary.TryGetProperty(program, out var progData) &&
            progData.TryGetProperty("controllers", out var controllers))
        {
            foreach (var c in controllers.EnumerateArray())
            {
                var name = c.GetString();
                if (!string.IsNullOrEmpty(name))
                    names.Add(name);
            }
        }
        return names;
    }

    private static bool HasControllerBase(JsonElement entry)
    {
        if (!entry.TryGetProperty("inherits", out var inherits)) return false;
        foreach (var i in inherits.EnumerateArray())
        {
            if (i.GetString() == "ControllerBase") return true;
        }
        return false;
    }

    private static void EmitController(StringBuilder sb, JsonElement entry, string name, JsonElement methods)
    {
        // Extract route attribute
        var routeTemplate = "api/[controller]";
        if (entry.TryGetProperty("attributes", out var attrs))
        {
            foreach (var attr in attrs.EnumerateArray())
            {
                var a = attr.GetString() ?? "";
                if (a.StartsWith("Route("))
                {
                    var start = a.IndexOf('"');
                    var end = a.LastIndexOf('"');
                    if (start >= 0 && end > start)
                        routeTemplate = a.Substring(start + 1, end - start - 1);
                    // Fix truncated route patterns from JSON
                    if (!routeTemplate.Contains("]"))
                        routeTemplate += "]";
                    if (routeTemplate == "api/[controller")
                        routeTemplate = "api/[controller]";
                }
            }
        }

        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Auto-generated controller: {name}");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("[ApiController]");
        sb.AppendLine($"[Route(\"{routeTemplate}\")]");
        sb.AppendLine($"public class {name} : ControllerBase");
        sb.AppendLine("{");
        sb.AppendLine($"    private readonly ILogger<{name}> _logger;");
        sb.AppendLine();
        sb.AppendLine($"    public {name}(ILogger<{name}> logger)");
        sb.AppendLine("    {");
        sb.AppendLine("        _logger = logger;");
        sb.AppendLine("    }");

        foreach (var method in methods.EnumerateArray())
        {
            EmitActionMethod(sb, method, name);
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void EmitActionMethod(StringBuilder sb, JsonElement method, string controllerName)
    {
        var methodName = method.TryGetProperty("name", out var mnEl) ? mnEl.GetString() ?? "UnknownAction" : "UnknownAction";
        var returnType = "Task<IActionResult>";
        if (method.TryGetProperty("returnType", out var rt))
        {
            var rtStr = rt.GetString() ?? "";
            if (rtStr.Contains("IActionResult"))
                returnType = rtStr;
            else
                returnType = "Task<IActionResult>";
        }

        sb.AppendLine();

        // Check for Authorize attribute
        bool hasAuthorize = false;
        string httpAttr = null;
        if (method.TryGetProperty("attributes", out var attrs))
        {
            foreach (var attr in attrs.EnumerateArray())
            {
                var a = attr.GetString() ?? "";
                if (a == "Authorize" || a.StartsWith("Authorize("))
                    hasAuthorize = true;
                if (a.StartsWith("Http"))
                    httpAttr = a;
            }
        }

        // Fallback: build HTTP attribute from httpMethod + actionRoute
        if (httpAttr == null)
        {
            var httpMethod = "Get";
            if (method.TryGetProperty("httpMethod", out var hm))
            {
                var hmStr = hm.GetString() ?? "GET";
                httpMethod = GeneratorHelpers.PascalCase(hmStr.ToLowerInvariant());
            }
            var actionRoute = "";
            if (method.TryGetProperty("actionRoute", out var ar))
                actionRoute = ar.GetString() ?? "";

            httpAttr = string.IsNullOrEmpty(actionRoute)
                ? $"Http{httpMethod}"
                : $"Http{httpMethod}(\"{actionRoute}\")";
        }

        // XML doc
        sb.AppendLine($"    /// <summary>{methodName} action.</summary>");

        if (hasAuthorize)
            sb.AppendLine("    [Authorize]");
        sb.AppendLine($"    [{httpAttr}]");

        // Build parameters
        var paramList = new List<string>();
        var usedParamNames = new HashSet<string>();
        if (method.TryGetProperty("parameters", out var parameters))
        {
            foreach (var param in parameters.EnumerateArray())
            {
                var paramName = param.TryGetProperty("name", out var pnEl) ? pnEl.GetString() ?? "param" : "param";
                paramName = GeneratorHelpers.SanitizeIdentifier(paramName);

                // Deduplicate parameter names
                var uniqueParamName = paramName;
                int paramSuffix = 2;
                while (usedParamNames.Contains(uniqueParamName))
                {
                    uniqueParamName = paramName + paramSuffix;
                    paramSuffix++;
                }
                usedParamNames.Add(uniqueParamName);

                var paramType = "";
                if (param.TryGetProperty("type", out var pt))
                    paramType = pt.GetString() ?? "object";

                var (bindingAttr, typeName) = GeneratorHelpers.ExtractFromAttribute(paramType);

                // Use 'object' for unknown custom types in parameter binding
                var cleanType = GeneratorHelpers.CleanPropertyType(typeName);

                var paramStr = bindingAttr != null
                    ? $"[{bindingAttr}] {cleanType} {uniqueParamName}"
                    : $"{cleanType} {uniqueParamName}";

                paramList.Add(paramStr);
            }
        }

        var paramsStr = string.Join(", ", paramList);
        sb.AppendLine($"    public {returnType} {GeneratorHelpers.SanitizeIdentifier(methodName)}({paramsStr})");
        sb.AppendLine("    {");
        sb.AppendLine($"        _logger.LogInformation(\"{methodName} called\");");
        sb.AppendLine("        throw new System.NotImplementedException();");
        sb.AppendLine("    }");
    }

    private static Dictionary<string, List<JsonElement>> GroupUnmatchedByTag(JsonDocument mappingDoc, string program)
    {
        var groups = new Dictionary<string, List<JsonElement>>();

        if (!mappingDoc.RootElement.TryGetProperty("unmatchedOperations", out var ops))
            return groups;

        foreach (var op in ops.EnumerateArray())
        {
            if (!op.TryGetProperty("program", out var progEl) || progEl.GetString() != program) continue;

            string tag = "General";
            if (op.TryGetProperty("tags", out var tags))
            {
                var firstTag = tags.EnumerateArray().FirstOrDefault();
                if (firstTag.ValueKind == JsonValueKind.String)
                    tag = firstTag.GetString() ?? "General";
            }

            var controllerName = GeneratorHelpers.PascalCase(
                GeneratorHelpers.SanitizeIdentifier(tag)) + "Controller";

            if (!groups.ContainsKey(controllerName))
                groups[controllerName] = new List<JsonElement>();
            groups[controllerName].Add(op);
        }

        return groups;
    }

    private static void EmitSyntheticController(StringBuilder sb, string controllerName, List<JsonElement> operations)
    {
        // Derive route from controller name: "EventsController" → "api/events"
        var baseName = controllerName.EndsWith("Controller")
            ? controllerName.Substring(0, controllerName.Length - "Controller".Length)
            : controllerName;
        var routeBase = "api/" + baseName.ToLowerInvariant();

        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Auto-generated controller from unmatched OpenAPI operations: {baseName}");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("[ApiController]");
        sb.AppendLine($"[Route(\"{routeBase}\")]");
        sb.AppendLine($"public class {controllerName} : ControllerBase");
        sb.AppendLine("{");
        sb.AppendLine($"    private readonly ILogger<{controllerName}> _logger;");
        sb.AppendLine();
        sb.AppendLine($"    public {controllerName}(ILogger<{controllerName}> logger)");
        sb.AppendLine("    {");
        sb.AppendLine("        _logger = logger;");
        sb.AppendLine("    }");

        var emittedMethods = new HashSet<string>();

        foreach (var op in operations)
        {
            var opId = op.TryGetProperty("operationId", out var oid) ? oid.GetString() ?? "" : "";
            var httpMethod = op.TryGetProperty("method", out var m) ? m.GetString()?.ToUpperInvariant() ?? "GET" : "GET";
            var path = op.TryGetProperty("path", out var p) ? p.GetString() ?? "/" : "/";
            var summary = op.TryGetProperty("summary", out var s) ? s.GetString() ?? "" : "";

            var methodName = GeneratorHelpers.ExtractOperationName(opId, httpMethod, path);

            // Deduplicate method names within same controller
            var uniqueName = methodName;
            int suffix = 2;
            while (emittedMethods.Contains(uniqueName))
            {
                uniqueName = methodName + suffix;
                suffix++;
            }
            emittedMethods.Add(uniqueName);

            // Determine route suffix: strip the base route prefix from the path
            var actionRoute = "";
            var pathLower = path.ToLowerInvariant();
            if (pathLower.StartsWith("/" + routeBase))
                actionRoute = path.Substring(("/" + routeBase).Length).TrimStart('/');
            else if (pathLower.StartsWith(routeBase))
                actionRoute = path.Substring(routeBase.Length).TrimStart('/');

            // Map HTTP method to attribute
            var httpAttr = httpMethod switch
            {
                "POST" => "HttpPost",
                "PUT" => "HttpPut",
                "DELETE" => "HttpDelete",
                "PATCH" => "HttpPatch",
                _ => "HttpGet"
            };

            sb.AppendLine();
            if (!string.IsNullOrEmpty(summary))
            {
                sb.AppendLine($"    /// <summary>{EscapeXml(summary)}</summary>");
            }

            if (!string.IsNullOrEmpty(actionRoute))
                sb.AppendLine($"    [{httpAttr}(\"{actionRoute}\")]");
            else
                sb.AppendLine($"    [{httpAttr}]");

            sb.AppendLine($"    public Task<IActionResult> {uniqueName}()");
            sb.AppendLine("    {");
            sb.AppendLine($"        _logger.LogInformation(\"{uniqueName} called\");");
            sb.AppendLine("        throw new System.NotImplementedException();");
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void GenerateDtos(SourceProductionContext ctx,
        JsonDocument controllersDoc, JsonDocument mappingDoc, string program, string rootNs)
    {
        if (controllersDoc == null) return;

        // Collect parameter type names referenced by controllers in this program
        var referencedTypes = CollectReferencedTypes(controllersDoc, mappingDoc, program);
        if (referencedTypes.Count == 0) return;

        // Find DTO entries in Controllers.json (have properties, no methods or no ControllerBase inheritance)
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Controller DTOs generated by TheWatch.Generators.RestApiControllerGenerator");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNs}.Controllers.Dtos;");
        sb.AppendLine();

        int dtoCount = 0;

        if (controllersDoc.RootElement.TryGetProperty("entries", out var entries))
        {
            foreach (var entry in entries.EnumerateArray())
            {
                if (!entry.TryGetProperty("name", out var nameEl2)) continue;
                var name = nameEl2.GetString() ?? "";
                if (!referencedTypes.Contains(name)) continue;
                if (!entry.TryGetProperty("properties", out var props)) continue;
                // Skip if it's a real controller (has methods + ControllerBase)
                if (entry.TryGetProperty("methods", out _) && HasControllerBase(entry)) continue;

                sb.AppendLine($"/// <summary>Auto-generated DTO: {name}</summary>");
                sb.AppendLine($"public class {GeneratorHelpers.SanitizeIdentifier(name)}");
                sb.AppendLine("{");

                foreach (var prop in props.EnumerateArray())
                {
                    var propName = prop.TryGetProperty("name", out var propNameEl) ? propNameEl.GetString() ?? "Unknown" : "Unknown";
                    var propType = "object";
                    if (prop.TryGetProperty("type", out var pt))
                        propType = GeneratorHelpers.CleanPropertyType(pt.GetString() ?? "object");

                    sb.AppendLine($"    public {propType} {GeneratorHelpers.SanitizeIdentifier(propName)} {{ get; set; }}");
                }

                sb.AppendLine("}");
                sb.AppendLine();
                dtoCount++;
            }
        }

        if (dtoCount == 0) return;

        ctx.AddSource("ControllerDtos.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static HashSet<string> CollectReferencedTypes(JsonDocument controllersDoc, JsonDocument mappingDoc, string program)
    {
        var types = new HashSet<string>();
        var programControllerNames = GetProgramControllerNames(mappingDoc, program);

        if (controllersDoc.RootElement.TryGetProperty("entries", out var entries))
        {
            foreach (var entry in entries.EnumerateArray())
            {
                if (!entry.TryGetProperty("name", out var nameEl3)) continue;
                var name = nameEl3.GetString() ?? "";
                if (!programControllerNames.Contains(name)) continue;
                if (!entry.TryGetProperty("methods", out var methods)) continue;

                foreach (var method in methods.EnumerateArray())
                {
                    if (!method.TryGetProperty("parameters", out var parameters)) continue;
                    foreach (var param in parameters.EnumerateArray())
                    {
                        if (!param.TryGetProperty("type", out var pt)) continue;
                        var rawType = pt.GetString() ?? "";
                        var (_, typeName) = GeneratorHelpers.ExtractFromAttribute(rawType);
                        // Only track types that look like custom DTO names (PascalCase, not a keyword)
                        if (!string.IsNullOrEmpty(typeName) && char.IsUpper(typeName[0]) &&
                            !IsBuiltInType(typeName))
                        {
                            types.Add(typeName);
                        }
                    }
                }
            }
        }

        return types;
    }

    private static bool IsBuiltInType(string typeName)
    {
        var builtIns = new HashSet<string>
        {
            "string", "int", "long", "short", "byte", "float", "double", "decimal",
            "bool", "char", "object", "dynamic", "void", "Guid", "DateTime",
            "DateTimeOffset", "TimeSpan", "Uri", "Task", "IActionResult",
            "CancellationToken"
        };
        return builtIns.Contains(typeName);
    }

    private static void GenerateSetup(SourceProductionContext ctx, string rootNs)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// REST API controller setup generated by TheWatch.Generators.RestApiControllerGenerator");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNs};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Extension methods to enable MVC controllers alongside minimal APIs.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class RestApiSetup");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Adds MVC controller services to the DI container.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static WebApplicationBuilder AddWatchControllers(this WebApplicationBuilder builder)");
        sb.AppendLine("    {");
        sb.AppendLine("        builder.Services.AddControllers();");
        sb.AppendLine("        return builder;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Maps MVC controller endpoints into the application pipeline.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static WebApplication MapWatchControllers(this WebApplication app)");
        sb.AppendLine("    {");
        sb.AppendLine("        app.MapControllers();");
        sb.AppendLine("        return app;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource("RestApiSetup.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string EscapeXml(string text)
    {
        if (string.IsNullOrEmpty(text)) return "";
        return text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
    }
}
