using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace TheWatch.Generators;

[Generator]
public class SecurityGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var projectInfo = context.AnalyzerConfigOptionsProvider
            .Select((opts, _) =>
            {
                opts.GlobalOptions.TryGetValue("build_property.RootNamespace", out var ns);
                opts.GlobalOptions.TryGetValue("build_property.UseMaui", out var useMaui);
                return (Namespace: ns ?? "TheWatch", UseMaui: useMaui ?? "");
            });

        context.RegisterSourceOutput(projectInfo, (spc, info) =>
        {
            var rootNs = info.Namespace;
            // Skip test projects, the generator itself, and MAUI projects
            if (rootNs.Contains(".Tests") || rootNs.Contains(".Generators"))
                return;
            if (info.UseMaui.Equals("true", System.StringComparison.OrdinalIgnoreCase) ||
                rootNs.Contains(".Mobile"))
                return;

            var program = GeneratorHelpers.DetectProgram(rootNs);
            var isP5 = program == "P5";
            var isAspire = rootNs.Contains("AppHost");
            if (isAspire) return;

            EmitSecuritySetup(spc, rootNs, program, isP5);
        });
    }

    private static void EmitSecuritySetup(SourceProductionContext ctx, string rootNs,
        string program, bool isP5)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Security configuration generated by TheWatch.Generators.SecurityGenerator");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Diagnostics;");
        sb.AppendLine("using System.Security.Claims;");
        sb.AppendLine("using System.Text;");
        sb.AppendLine("using System.Threading.RateLimiting;");
        sb.AppendLine("using Microsoft.AspNetCore.Authentication;");
        sb.AppendLine("using Microsoft.AspNetCore.Authentication.JwtBearer;");
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.AspNetCore.Http;");
        sb.AppendLine("using Microsoft.AspNetCore.RateLimiting;");
        sb.AppendLine("using Microsoft.Extensions.Configuration;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.Logging;");
        sb.AppendLine("using Microsoft.IdentityModel.Tokens;");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNs};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Auto-generated security configuration for {rootNs}.");
        sb.AppendLine("/// Provides rate limiting, authorization policies, and audit middleware.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class SecuritySetup");
        sb.AppendLine("{");

        // === AddWatchSecurity ===
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers JWT authentication, authorization policies, rate limiting, and API key auth.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static WebApplicationBuilder AddWatchSecurity(this WebApplicationBuilder builder)");
        sb.AppendLine("    {");
        sb.AppendLine("        var config = builder.Configuration;");

        if (!isP5)
        {
            // Consumer services: add JWT validation + policies
            sb.AppendLine();
            sb.AppendLine("        // JWT Bearer authentication — supports asymmetric RSA (prod) and symmetric HMAC (dev)");
            sb.AppendLine("        var asymmetricKeyPath = config[\"Jwt:AsymmetricPublicKeyPath\"];");
            sb.AppendLine("        Microsoft.IdentityModel.Tokens.SecurityKey signingKey;");
            sb.AppendLine("        if (!string.IsNullOrEmpty(asymmetricKeyPath) && System.IO.File.Exists(asymmetricKeyPath))");
            sb.AppendLine("        {");
            sb.AppendLine("            var rsa = System.Security.Cryptography.RSA.Create();");
            sb.AppendLine("            rsa.ImportFromPem(System.IO.File.ReadAllText(asymmetricKeyPath));");
            sb.AppendLine("            signingKey = new Microsoft.IdentityModel.Tokens.RsaSecurityKey(rsa);");
            sb.AppendLine("        }");
            sb.AppendLine("        else");
            sb.AppendLine("        {");
            sb.AppendLine("            var jwtKey = config[\"Jwt:Key\"] ?? throw new InvalidOperationException(\"FATAL: Neither Jwt:AsymmetricPublicKeyPath nor Jwt:Key configured.\");");
            sb.AppendLine("            signingKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtKey));");
            sb.AppendLine("        }");
            sb.AppendLine("        var jwtIssuer = config[\"Jwt:Issuer\"] ?? \"TheWatch.P5.AuthSecurity\";");
            sb.AppendLine("        var jwtAudience = config[\"Jwt:Audience\"] ?? \"TheWatch\";");
            sb.AppendLine();
            sb.AppendLine("        builder.Services.AddAuthentication(options =>");
            sb.AppendLine("        {");
            sb.AppendLine("            options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;");
            sb.AppendLine("            options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;");
            sb.AppendLine("        })");
            sb.AppendLine("        .AddJwtBearer(options =>");
            sb.AppendLine("        {");
            sb.AppendLine("            options.TokenValidationParameters = new TokenValidationParameters");
            sb.AppendLine("            {");
            sb.AppendLine("                ValidateIssuer = true,");
            sb.AppendLine("                ValidateAudience = true,");
            sb.AppendLine("                ValidateLifetime = true,");
            sb.AppendLine("                ValidateIssuerSigningKey = true,");
            sb.AppendLine("                ValidIssuer = jwtIssuer,");
            sb.AppendLine("                ValidAudience = jwtAudience,");
            sb.AppendLine("                IssuerSigningKey = signingKey,");
            sb.AppendLine("                ClockSkew = TimeSpan.FromSeconds(30),");
            sb.AppendLine("                RequireExpirationTime = true");
            sb.AppendLine("            };");
            sb.AppendLine();
            sb.AppendLine("            // Support SignalR token via query string");
            sb.AppendLine("            options.Events = new JwtBearerEvents");
            sb.AppendLine("            {");
            sb.AppendLine("                OnMessageReceived = context =>");
            sb.AppendLine("                {");
            sb.AppendLine("                    var accessToken = context.Request.Query[\"access_token\"];");
            sb.AppendLine("                    var path = context.HttpContext.Request.Path;");
            sb.AppendLine("                    if (!string.IsNullOrEmpty(accessToken) && path.StartsWithSegments(\"/hubs\"))");
            sb.AppendLine("                    {");
            sb.AppendLine("                        context.Token = accessToken;");
            sb.AppendLine("                    }");
            sb.AppendLine("                    return System.Threading.Tasks.Task.CompletedTask;");
            sb.AppendLine("                }");
            sb.AppendLine("            };");
            sb.AppendLine("        })");
            sb.AppendLine("        .AddScheme<AuthenticationSchemeOptions, TheWatch.Shared.Security.ApiKeyAuthHandler>(");
            sb.AppendLine("            \"ApiKey\", _ => { });");
        }

        // Authorization policies (all services)
        sb.AppendLine();
        sb.AppendLine("        // Authorization policies");
        sb.AppendLine("        builder.Services.AddAuthorizationBuilder()");
        sb.AppendLine("            .AddPolicy(\"AdminOnly\", policy =>");
        sb.AppendLine("                policy.RequireRole(\"Admin\"))");
        sb.AppendLine("            .AddPolicy(\"ResponderAccess\", policy =>");
        sb.AppendLine("                policy.RequireRole(\"Admin\", \"Responder\"))");
        sb.AppendLine("            .AddPolicy(\"DoctorAccess\", policy =>");
        sb.AppendLine("                policy.RequireRole(\"Admin\", \"Doctor\"))");
        sb.AppendLine("            .AddPolicy(\"FamilyAccess\", policy =>");
        sb.AppendLine("                policy.RequireRole(\"Admin\", \"FamilyMember\", \"Patient\"))");
        sb.AppendLine("            .AddPolicy(\"ServiceToService\", policy =>");
        sb.AppendLine("                policy.RequireRole(\"Admin\", \"ServiceAccount\"))");
        sb.AppendLine("            .AddPolicy(\"Authenticated\", policy =>");
        sb.AppendLine("                policy.RequireAuthenticatedUser());");

        // Rate limiting (all services)
        sb.AppendLine();
        sb.AppendLine("        // Rate limiting");
        sb.AppendLine("        builder.Services.AddRateLimiter(options =>");
        sb.AppendLine("        {");
        sb.AppendLine("            options.RejectionStatusCode = 429;");
        sb.AppendLine();
        sb.AppendLine("            // Global: 100 requests/minute per IP");
        sb.AppendLine("            options.AddFixedWindowLimiter(\"GlobalLimit\", opt =>");
        sb.AppendLine("            {");
        sb.AppendLine("                opt.PermitLimit = 100;");
        sb.AppendLine("                opt.Window = TimeSpan.FromMinutes(1);");
        sb.AppendLine("                opt.QueueProcessingOrder = QueueProcessingOrder.OldestFirst;");
        sb.AppendLine("                opt.QueueLimit = 10;");
        sb.AppendLine("            });");
        sb.AppendLine();
        sb.AppendLine("            // Auth endpoints: 10 requests/minute per IP");
        sb.AppendLine("            options.AddSlidingWindowLimiter(\"AuthLimit\", opt =>");
        sb.AppendLine("            {");
        sb.AppendLine("                opt.PermitLimit = 10;");
        sb.AppendLine("                opt.Window = TimeSpan.FromMinutes(1);");
        sb.AppendLine("                opt.SegmentsPerWindow = 4;");
        sb.AppendLine("                opt.QueueProcessingOrder = QueueProcessingOrder.OldestFirst;");
        sb.AppendLine("                opt.QueueLimit = 2;");
        sb.AppendLine("            });");
        sb.AppendLine();
        sb.AppendLine("            // Authenticated API: 60 requests/minute per user");
        sb.AppendLine("            options.AddFixedWindowLimiter(\"ApiLimit\", opt =>");
        sb.AppendLine("            {");
        sb.AppendLine("                opt.PermitLimit = 60;");
        sb.AppendLine("                opt.Window = TimeSpan.FromMinutes(1);");
        sb.AppendLine("                opt.QueueProcessingOrder = QueueProcessingOrder.OldestFirst;");
        sb.AppendLine("                opt.QueueLimit = 5;");
        sb.AppendLine("            });");
        sb.AppendLine();
        sb.AppendLine("            // Security+ 2.4: MFA/magic-link endpoint limit (3 req/min)");
        sb.AppendLine("            options.AddSlidingWindowLimiter(\"MfaLimit\", opt =>");
        sb.AppendLine("            {");
        sb.AppendLine("                opt.PermitLimit = 3;");
        sb.AppendLine("                opt.Window = TimeSpan.FromMinutes(1);");
        sb.AppendLine("                opt.SegmentsPerWindow = 2;");
        sb.AppendLine("                opt.QueueProcessingOrder = QueueProcessingOrder.OldestFirst;");
        sb.AppendLine("                opt.QueueLimit = 0;");
        sb.AppendLine("            });");
        sb.AppendLine();
        sb.AppendLine("            // Security+ 2.5: Per-user rate limiting (authenticated → userId, anonymous → IP)");
        sb.AppendLine("            options.GlobalLimiter = PartitionedRateLimiter.Create<HttpContext, string>(context =>");
        sb.AppendLine("            {");
        sb.AppendLine("                var userId = context.User?.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value;");
        sb.AppendLine("                var partitionKey = !string.IsNullOrEmpty(userId)");
        sb.AppendLine("                    ? $\"user:{userId}\"");
        sb.AppendLine("                    : $\"ip:{context.Connection.RemoteIpAddress?.ToString() ?? \"unknown\"}\";");
        sb.AppendLine("                return RateLimitPartition.GetFixedWindowLimiter(partitionKey, _ => new FixedWindowRateLimiterOptions");
        sb.AppendLine("                {");
        sb.AppendLine("                    PermitLimit = 100,");
        sb.AppendLine("                    Window = TimeSpan.FromMinutes(1)");
        sb.AppendLine("                });");
        sb.AppendLine("            });");
        sb.AppendLine("        });");

        sb.AppendLine();
        sb.AppendLine("        return builder;");
        sb.AppendLine("    }");

        // === UseWatchSecurity ===
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Applies rate limiting and audit middleware to the request pipeline.");
        sb.AppendLine("    /// Call after UseCors() and before UseAuthentication().");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static WebApplication UseWatchSecurity(this WebApplication app)");
        sb.AppendLine("    {");
        sb.AppendLine("        // Security+ 2.2: OWASP security headers on all responses");
        sb.AppendLine("        app.UseMiddleware<TheWatch.Shared.Security.SecurityHeadersMiddleware>();");
        sb.AppendLine("        app.UseRateLimiter();");
        sb.AppendLine("        app.UseMiddleware<TheWatch.Shared.Security.SecurityAuditMiddleware>();");
        sb.AppendLine("        app.UseMiddleware<TheWatch.Shared.Security.WatchProblemDetailsMiddleware>();");
        sb.AppendLine("        app.UseMiddleware<TheWatch.Shared.Security.CuiMarkingMiddleware>();");
        sb.AppendLine("        return app;");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        ctx.AddSource("SecuritySetup.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
