using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace TheWatch.Generators;

[Generator]
public class ServiceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var mappingFiles = context.AdditionalTextsProvider
            .Where(f => f.Path.EndsWith("_mapping.json"));

        var interfaceFiles = context.AdditionalTextsProvider
            .Where(f => f.Path.EndsWith("Interfaces.json"));

        var projectName = context.AnalyzerConfigOptionsProvider
            .Select((opts, _) =>
            {
                opts.GlobalOptions.TryGetValue("build_property.RootNamespace", out var ns);
                return ns ?? "TheWatch";
            });

        var combined = mappingFiles.Collect()
            .Combine(interfaceFiles.Collect())
            .Combine(projectName);

        context.RegisterSourceOutput(combined, (spc, pair) =>
        {
            var ((mappingTexts, ifaceTexts), rootNs) = pair;
            if (mappingTexts.IsEmpty) return;
            if (rootNs.Contains(".Tests")) return;

            var program = GeneratorHelpers.DetectProgram(rootNs);
            if (program == null) return;

            var mappingText = mappingTexts[0].GetText()?.ToString();
            if (mappingText == null) return;
            var mapping = JsonDocument.Parse(mappingText).RootElement;

            GenerateServiceInterfaces(spc, mapping, program, rootNs);
            GenerateServiceStubs(spc, mapping, program, rootNs);

            // Generate from consolidated interfaces if available
            if (!ifaceTexts.IsEmpty)
            {
                var ifaceText = ifaceTexts[0].GetText()?.ToString();
                if (ifaceText != null)
                {
                    var ifaces = JsonDocument.Parse(ifaceText).RootElement;
                    GenerateConsolidatedInterfaces(spc, ifaces, mapping, program, rootNs);
                }
            }
        });
    }

    private static void GenerateServiceInterfaces(SourceProductionContext ctx,
        JsonElement mapping, string program, string rootNs)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNs}.Services;");
        sb.AppendLine();

        var emitted = new HashSet<string>();

        // From controller matches
        if (mapping.TryGetProperty("controllerMatches", out var ctrlMatches))
        {
            foreach (var m in ctrlMatches.EnumerateArray())
            {
                if (m.GetProperty("program").GetString() != program) continue;
                var opId = m.GetProperty("operationId").GetString() ?? "";
                var httpMethod = m.GetProperty("httpMethod").GetString() ?? "GET";
                var path = m.GetProperty("operationPath").GetString() ?? "/";
                var methodName = GeneratorHelpers.ExtractOperationName(opId, httpMethod, path);
                var ifaceName = $"I{methodName}Service";
                if (!emitted.Add(ifaceName)) continue;

                sb.AppendLine($"public interface {ifaceName}");
                sb.AppendLine("{");
                sb.AppendLine($"    Task<object> ExecuteAsync();");
                sb.AppendLine("}");
                sb.AppendLine();
            }
        }

        // From unmatched operations
        if (mapping.TryGetProperty("unmatchedOperations", out var unmatchedOps))
        {
            foreach (var op in unmatchedOps.EnumerateArray())
            {
                if (op.GetProperty("program").GetString() != program) continue;
                var opId = op.GetProperty("operationId").GetString() ?? "";
                var httpMethod = op.GetProperty("method").GetString() ?? "GET";
                var path = op.GetProperty("path").GetString() ?? "/";
                var methodName = GeneratorHelpers.ExtractOperationName(opId, httpMethod, path);
                var ifaceName = $"I{methodName}Service";
                if (!emitted.Add(ifaceName)) continue;

                var summary = op.GetProperty("summary").GetString() ?? "";
                if (!string.IsNullOrEmpty(summary))
                    sb.AppendLine($"/// <summary>{summary}</summary>");

                sb.AppendLine($"public interface {ifaceName}");
                sb.AppendLine("{");
                sb.AppendLine($"    Task<object> ExecuteAsync();");
                sb.AppendLine("}");
                sb.AppendLine();
            }
        }

        ctx.AddSource("ServiceInterfaces.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void GenerateServiceStubs(SourceProductionContext ctx,
        JsonElement mapping, string program, string rootNs)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.Logging;");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNs}.Services;");
        sb.AppendLine();

        var emitted = new HashSet<string>();

        void EmitStub(string methodName, string summary)
        {
            var ifaceName = $"I{methodName}Service";
            var className = $"{methodName}Service";
            if (!emitted.Add(className)) return;

            sb.AppendLine($"public class {className} : {ifaceName}");
            sb.AppendLine("{");
            sb.AppendLine($"    private readonly ILogger<{className}> _logger;");
            sb.AppendLine();
            sb.AppendLine($"    public {className}(ILogger<{className}> logger)");
            sb.AppendLine("    {");
            sb.AppendLine("        _logger = logger;");
            sb.AppendLine("    }");
            sb.AppendLine();
            if (!string.IsNullOrEmpty(summary))
                sb.AppendLine($"    /// <summary>{summary}</summary>");
            sb.AppendLine($"    public Task<object> ExecuteAsync()");
            sb.AppendLine("    {");
            sb.AppendLine($"        _logger.LogInformation(\"Executing {methodName}\");");
            sb.AppendLine("        throw new System.NotImplementedException();");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        if (mapping.TryGetProperty("controllerMatches", out var ctrlMatches))
        {
            foreach (var m in ctrlMatches.EnumerateArray())
            {
                if (m.GetProperty("program").GetString() != program) continue;
                var opId = m.GetProperty("operationId").GetString() ?? "";
                var httpMethod = m.GetProperty("httpMethod").GetString() ?? "GET";
                var path = m.GetProperty("operationPath").GetString() ?? "/";
                var methodName = GeneratorHelpers.ExtractOperationName(opId, httpMethod, path);
                var summary = m.GetProperty("operationSummary").GetString() ?? "";
                EmitStub(methodName, summary);
            }
        }

        if (mapping.TryGetProperty("unmatchedOperations", out var unmatchedOps))
        {
            foreach (var op in unmatchedOps.EnumerateArray())
            {
                if (op.GetProperty("program").GetString() != program) continue;
                var opId = op.GetProperty("operationId").GetString() ?? "";
                var httpMethod = op.GetProperty("method").GetString() ?? "GET";
                var path = op.GetProperty("path").GetString() ?? "/";
                var methodName = GeneratorHelpers.ExtractOperationName(opId, httpMethod, path);
                var summary = op.GetProperty("summary").GetString() ?? "";
                EmitStub(methodName, summary);
            }
        }

        ctx.AddSource("ServiceStubs.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void GenerateConsolidatedInterfaces(SourceProductionContext ctx,
        JsonElement ifacesDoc, JsonElement mapping, string program, string rootNs)
    {
        if (!ifacesDoc.TryGetProperty("entries", out var entries)) return;

        // Get interfaces assigned to this program
        var programIfaces = new HashSet<string>();
        if (mapping.TryGetProperty("interfaceAssignments", out var assignments))
        {
            foreach (var a in assignments.EnumerateArray())
            {
                if (a.GetProperty("program").GetString() == program)
                    programIfaces.Add(a.GetProperty("interface").GetString() ?? "");
            }
        }

        if (!programIfaces.Any()) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Consolidated interfaces from existing codebase");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNs}.Contracts;");
        sb.AppendLine();

        var emitted = new HashSet<string>();

        foreach (var entry in entries.EnumerateArray())
        {
            var name = entry.GetProperty("name").GetString() ?? "";
            if (!programIfaces.Contains(name)) continue;
            var safeName = GeneratorHelpers.SanitizeIdentifier(name);
            if (!emitted.Add(safeName)) continue;

            var kind = entry.TryGetProperty("kind", out var k) ? k.GetString() : "interface";
            var keyword = kind == "interface" ? "interface" : "class";

            sb.AppendLine($"public {keyword} {safeName}");
            sb.AppendLine("{");

            if (entry.TryGetProperty("properties", out var props))
            {
                foreach (var prop in props.EnumerateArray())
                {
                    var propName = prop.TryGetProperty("name", out var pn) ? pn.GetString() : null;
                    if (string.IsNullOrEmpty(propName)) continue;
                    var rawType = prop.TryGetProperty("type", out var pt) ? pt.GetString() : "object";
                    var propType = GeneratorHelpers.CleanPropertyType(rawType ?? "object");
                    var safeProp = GeneratorHelpers.SanitizeIdentifier(propName!);
                    sb.AppendLine($"    {propType} {safeProp} {{ get; set; }}");
                }
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }

        ctx.AddSource("ConsolidatedInterfaces.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
