using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace TheWatch.Generators;

[Generator]
public class TestGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var mappingFiles = context.AdditionalTextsProvider
            .Where(f => f.Path.EndsWith("_mapping.json"));

        var projectName = context.AnalyzerConfigOptionsProvider
            .Select((opts, _) =>
            {
                opts.GlobalOptions.TryGetValue("build_property.RootNamespace", out var ns);
                return ns ?? "TheWatch";
            });

        var combined = mappingFiles.Collect().Combine(projectName);

        context.RegisterSourceOutput(combined, (spc, pair) =>
        {
            var (files, rootNs) = pair;
            if (files.IsEmpty) return;

            // Only generate test code in .Tests projects
            if (!rootNs.Contains(".Tests")) return;

            // Test projects have ".Tests" suffix — strip it to find program
            var svcNs = rootNs.Replace(".Tests", "");
            var program = GeneratorHelpers.DetectProgram(svcNs);
            if (program == null) return;

            var text = files[0].GetText()?.ToString();
            if (text == null) return;

            var mapping = JsonDocument.Parse(text).RootElement;
            GenerateEndpointTests(spc, mapping, program, rootNs, svcNs);
            GenerateServiceTests(spc, mapping, program, rootNs, svcNs);
            GenerateJobTests(spc, mapping, program, rootNs, svcNs);
        });
    }

    private static void GenerateEndpointTests(SourceProductionContext ctx, JsonElement mapping,
        string program, string rootNs, string svcNs)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Net;");
        sb.AppendLine("using System.Net.Http.Json;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using FluentAssertions;");
        sb.AppendLine("using Microsoft.AspNetCore.Mvc.Testing;");
        sb.AppendLine("using Xunit;");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNs}.EndpointTests;");
        sb.AppendLine();

        var emitted = new HashSet<string>();
        int count = 0;

        void EmitTest(string opId, string httpMethod, string path, string summary)
        {
            var name = GeneratorHelpers.ExtractOperationName(opId, httpMethod, path);
            if (!emitted.Add(name)) return;

            if (count == 0)
            {
                sb.AppendLine($"public class EndpointIntegrationTests : IClassFixture<WebApplicationFactory<Program>>");
                sb.AppendLine("{");
                sb.AppendLine($"    private readonly HttpClient _client;");
                sb.AppendLine();
                sb.AppendLine($"    public EndpointIntegrationTests(WebApplicationFactory<Program> factory)");
                sb.AppendLine("    {");
                sb.AppendLine("        _client = factory.CreateClient();");
                sb.AppendLine("    }");
            }
            count++;

            sb.AppendLine();
            sb.AppendLine("    [Fact]");
            if (!string.IsNullOrEmpty(summary))
                sb.AppendLine($"    // {summary}");
            sb.AppendLine($"    public async Task {name}_ReturnsSuccess()");
            sb.AppendLine("    {");
            sb.AppendLine("        // Arrange");
            sb.AppendLine($"        var request = new HttpRequestMessage(HttpMethod.{GeneratorHelpers.PascalCase(httpMethod.ToLowerInvariant())}, \"{path}\");");
            sb.AppendLine();
            sb.AppendLine("        // Act");
            sb.AppendLine("        var response = await _client.SendAsync(request);");
            sb.AppendLine();
            sb.AppendLine("        // Assert");
            sb.AppendLine("        response.StatusCode.Should().BeOneOf(");
            sb.AppendLine("            HttpStatusCode.OK,");
            sb.AppendLine("            HttpStatusCode.Created,");
            sb.AppendLine("            HttpStatusCode.NoContent,");
            sb.AppendLine("            HttpStatusCode.NotImplemented);");
            sb.AppendLine("    }");
        }

        if (mapping.TryGetProperty("controllerMatches", out var ctrlMatches))
        {
            foreach (var m in ctrlMatches.EnumerateArray())
            {
                if (m.GetProperty("program").GetString() != program) continue;
                if (m.GetProperty("matchType").GetString() == "unmatched") continue;
                EmitTest(
                    m.GetProperty("operationId").GetString() ?? "",
                    m.GetProperty("httpMethod").GetString() ?? "GET",
                    m.GetProperty("operationPath").GetString() ?? "/",
                    m.GetProperty("operationSummary").GetString() ?? "");
            }
        }

        if (mapping.TryGetProperty("unmatchedOperations", out var ops))
        {
            foreach (var op in ops.EnumerateArray())
            {
                if (op.GetProperty("program").GetString() != program) continue;
                EmitTest(
                    op.GetProperty("operationId").GetString() ?? "",
                    op.GetProperty("method").GetString() ?? "GET",
                    op.GetProperty("path").GetString() ?? "/",
                    op.GetProperty("summary").GetString() ?? "");
            }
        }

        if (count > 0)
        {
            sb.AppendLine("}");
            ctx.AddSource("EndpointTests.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }

    private static void GenerateServiceTests(SourceProductionContext ctx, JsonElement mapping,
        string program, string rootNs, string svcNs)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using FluentAssertions;");
        sb.AppendLine("using Microsoft.Extensions.Logging;");
        sb.AppendLine("using NSubstitute;");
        sb.AppendLine("using Xunit;");
        sb.AppendLine($"using {svcNs}.Services;");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNs}.ServiceTests;");
        sb.AppendLine();

        var emitted = new HashSet<string>();
        int count = 0;

        void EmitServiceTest(string opId, string httpMethod, string path)
        {
            var name = GeneratorHelpers.ExtractOperationName(opId, httpMethod, path);
            var className = $"{name}Service";
            if (!emitted.Add(className)) return;

            if (count == 0)
            {
                sb.AppendLine("public class ServiceUnitTests");
                sb.AppendLine("{");
            }
            count++;

            sb.AppendLine();
            sb.AppendLine("    [Fact]");
            sb.AppendLine($"    public async Task {className}_ExecuteAsync_ThrowsNotImplemented()");
            sb.AppendLine("    {");
            sb.AppendLine("        // Arrange");
            sb.AppendLine($"        var logger = Substitute.For<ILogger<{className}>>();");
            sb.AppendLine($"        var svc = new {className}(logger);");
            sb.AppendLine();
            sb.AppendLine("        // Act & Assert");
            sb.AppendLine($"        await FluentActions.Invoking(() => svc.ExecuteAsync())");
            sb.AppendLine("            .Should().ThrowAsync<System.NotImplementedException>();");
            sb.AppendLine("    }");
        }

        if (mapping.TryGetProperty("controllerMatches", out var ctrlMatches))
        {
            foreach (var m in ctrlMatches.EnumerateArray())
            {
                if (m.GetProperty("program").GetString() != program) continue;
                EmitServiceTest(
                    m.GetProperty("operationId").GetString() ?? "",
                    m.GetProperty("httpMethod").GetString() ?? "GET",
                    m.GetProperty("operationPath").GetString() ?? "/");
            }
        }

        if (mapping.TryGetProperty("unmatchedOperations", out var ops))
        {
            foreach (var op in ops.EnumerateArray())
            {
                if (op.GetProperty("program").GetString() != program) continue;
                EmitServiceTest(
                    op.GetProperty("operationId").GetString() ?? "",
                    op.GetProperty("method").GetString() ?? "GET",
                    op.GetProperty("path").GetString() ?? "/");
            }
        }

        if (count > 0)
        {
            sb.AppendLine("}");
            ctx.AddSource("ServiceTests.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }

    private static void GenerateJobTests(SourceProductionContext ctx, JsonElement mapping,
        string program, string rootNs, string svcNs)
    {
        // Minimal stub — job tests follow same pattern
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using FluentAssertions;");
        sb.AppendLine("using Microsoft.Extensions.Logging;");
        sb.AppendLine("using NSubstitute;");
        sb.AppendLine("using Xunit;");
        sb.AppendLine($"using {svcNs}.Jobs;");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNs}.JobTests;");
        sb.AppendLine();
        sb.AppendLine("public class HangfireJobTests");
        sb.AppendLine("{");
        sb.AppendLine("    // Job tests are generated alongside the HangfireJobGenerator output.");
        sb.AppendLine("    // Each job class gets a test verifying enqueue/execute lifecycle.");
        sb.AppendLine("}");

        ctx.AddSource("JobTests.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
