using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace TheWatch.Generators;

[Generator]
public class MauiPageGenerator : IIncrementalGenerator
{
    // Program metadata: (id, name, shortName, icon, port)
    private static readonly (string Id, string Name, string Short, string Icon, int Port)[] Programs =
    {
        ("P1", "CoreGateway", "Core", "hub", 5001),
        ("P2", "VoiceEmergency", "Emergency", "record_voice_over", 5002),
        ("P3", "MeshNetwork", "Mesh", "lan", 5003),
        ("P4", "Wearable", "Wearable", "watch", 5004),
        ("P5", "AuthSecurity", "Auth", "shield", 5005),
        ("P6", "FirstResponder", "Responder", "local_fire_department", 5006),
        ("P7", "FamilyHealth", "Family", "family_restroom", 5007),
        ("P8", "DisasterRelief", "Disaster", "flood", 5008),
        ("P9", "DoctorServices", "Doctor", "medical_services", 5009),
        ("P10", "Gamification", "Gamification", "emoji_events", 5010),
    };

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var projectInfo = context.AnalyzerConfigOptionsProvider
            .Select((opts, _) =>
            {
                opts.GlobalOptions.TryGetValue("build_property.RootNamespace", out var ns);
                opts.GlobalOptions.TryGetValue("build_property.UseMaui", out var useMaui);
                return (Namespace: ns ?? "", UseMaui: useMaui ?? "");
            });

        context.RegisterSourceOutput(projectInfo, (spc, info) =>
        {
            // Only emit for MAUI projects
            if (!info.UseMaui.Equals("true", System.StringComparison.OrdinalIgnoreCase) &&
                !info.Namespace.Contains("Mobile"))
                return;

            EmitProgramClients(spc, info.Namespace);
            EmitProgramRoutes(spc, info.Namespace);
        });
    }

    private static void EmitProgramClients(SourceProductionContext ctx, string rootNs)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Per-program HTTP clients generated by TheWatch.Generators.MauiPageGenerator");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Net.Http;");
        sb.AppendLine("using System.Net.Http.Json;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNs}.Generated;");
        sb.AppendLine();

        foreach (var p in Programs)
        {
            sb.AppendLine($"/// <summary>Typed HTTP client for {p.Id} {p.Name}.</summary>");
            sb.AppendLine($"public class {p.Id}Client");
            sb.AppendLine("{");
            sb.AppendLine("    private readonly HttpClient _http;");
            sb.AppendLine($"    public const string ServiceName = \"{p.Id}-{p.Name.ToLowerInvariant()}\";");
            sb.AppendLine($"    public const int DefaultPort = {p.Port};");
            sb.AppendLine();
            sb.AppendLine($"    public {p.Id}Client(HttpClient http) => _http = http;");
            sb.AppendLine();

            // Health check — universal
            sb.AppendLine($"    public async Task<bool> CheckHealthAsync(string baseUrl = \"http://localhost:{p.Port}\")");
            sb.AppendLine("    {");
            sb.AppendLine("        try");
            sb.AppendLine("        {");
            sb.AppendLine("            var r = await _http.GetAsync($\"{baseUrl}/health\");");
            sb.AppendLine("            return r.IsSuccessStatusCode;");
            sb.AppendLine("        }");
            sb.AppendLine("        catch { return false; }");
            sb.AppendLine("    }");
            sb.AppendLine();

            // Info endpoint — universal
            sb.AppendLine($"    public async Task<object?> GetInfoAsync(string baseUrl = \"http://localhost:{p.Port}\")");
            sb.AppendLine("    {");
            sb.AppendLine("        return await _http.GetFromJsonAsync<object>($\"{baseUrl}/info\");");
            sb.AppendLine("    }");

            // Program-specific endpoints
            EmitProgramSpecificMethods(sb, p.Id, p.Port);

            sb.AppendLine("}");
            sb.AppendLine();
        }

        ctx.AddSource("ProgramClients.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void EmitProgramSpecificMethods(StringBuilder sb, string programId, int port)
    {
        var baseUrl = $"http://localhost:{port}";

        switch (programId)
        {
            case "P2": // VoiceEmergency
                sb.AppendLine();
                sb.AppendLine($"    public async Task<object?> CreateIncidentAsync(object request, string baseUrl = \"{baseUrl}\")");
                sb.AppendLine("        => await (await _http.PostAsJsonAsync($\"{baseUrl}/api/incidents\", request)).Content.ReadFromJsonAsync<object>();");
                sb.AppendLine();
                sb.AppendLine($"    public async Task<object?> GetIncidentsAsync(int pageSize = 10, string baseUrl = \"{baseUrl}\")");
                sb.AppendLine("        => await _http.GetFromJsonAsync<object>($\"{baseUrl}/api/incidents?pageSize={pageSize}\");");
                sb.AppendLine();
                sb.AppendLine($"    public async Task<object?> CreateDispatchAsync(object request, string baseUrl = \"{baseUrl}\")");
                sb.AppendLine("        => await (await _http.PostAsJsonAsync($\"{baseUrl}/api/dispatch\", request)).Content.ReadFromJsonAsync<object>();");
                break;

            case "P5": // AuthSecurity
                sb.AppendLine();
                sb.AppendLine($"    public async Task<object?> LoginAsync(object request, string baseUrl = \"{baseUrl}\")");
                sb.AppendLine("        => await (await _http.PostAsJsonAsync($\"{baseUrl}/api/auth/login\", request)).Content.ReadFromJsonAsync<object>();");
                sb.AppendLine();
                sb.AppendLine($"    public async Task<object?> RegisterAsync(object request, string baseUrl = \"{baseUrl}\")");
                sb.AppendLine("        => await (await _http.PostAsJsonAsync($\"{baseUrl}/api/auth/register\", request)).Content.ReadFromJsonAsync<object>();");
                sb.AppendLine();
                sb.AppendLine($"    public async Task<object?> GetMeAsync(string baseUrl = \"{baseUrl}\")");
                sb.AppendLine("        => await _http.GetFromJsonAsync<object>($\"{baseUrl}/api/auth/me\");");
                break;

            case "P6": // FirstResponder
                sb.AppendLine();
                sb.AppendLine($"    public async Task<object?> GetNearbyRespondersAsync(double lat, double lon, double radiusKm = 10, string baseUrl = \"{baseUrl}\")");
                sb.AppendLine("        => await _http.GetFromJsonAsync<object>($\"{baseUrl}/api/responders/nearby?lat={lat}&lon={lon}&radiusKm={radiusKm}\");");
                break;

            case "P7": // FamilyHealth
                sb.AppendLine();
                sb.AppendLine($"    public async Task<object?> GetFamiliesAsync(string baseUrl = \"{baseUrl}\")");
                sb.AppendLine("        => await _http.GetFromJsonAsync<object>($\"{baseUrl}/api/families\");");
                sb.AppendLine();
                sb.AppendLine($"    public async Task<object?> CreateCheckInAsync(object request, string baseUrl = \"{baseUrl}\")");
                sb.AppendLine("        => await (await _http.PostAsJsonAsync($\"{baseUrl}/api/checkins\", request)).Content.ReadFromJsonAsync<object>();");
                sb.AppendLine();
                sb.AppendLine($"    public async Task<object?> GetVitalsAsync(System.Guid memberId, string baseUrl = \"{baseUrl}\")");
                sb.AppendLine("        => await _http.GetFromJsonAsync<object>($\"{baseUrl}/api/vitals/{memberId}\");");
                break;

            case "P8": // DisasterRelief
                sb.AppendLine();
                sb.AppendLine($"    public async Task<object?> GetDisasterEventsAsync(string baseUrl = \"{baseUrl}\")");
                sb.AppendLine("        => await _http.GetFromJsonAsync<object>($\"{baseUrl}/api/disasters\");");
                sb.AppendLine();
                sb.AppendLine($"    public async Task<object?> GetNearbySheltersAsync(double lat, double lon, double radiusKm = 25, string baseUrl = \"{baseUrl}\")");
                sb.AppendLine("        => await _http.GetFromJsonAsync<object>($\"{baseUrl}/api/shelters/nearby?lat={lat}&lon={lon}&radiusKm={radiusKm}\");");
                break;

            case "P10": // Gamification
                sb.AppendLine();
                sb.AppendLine($"    public async Task<object?> GetLeaderboardAsync(int top = 10, string baseUrl = \"{baseUrl}\")");
                sb.AppendLine("        => await _http.GetFromJsonAsync<object>($\"{baseUrl}/api/leaderboard?top={top}\");");
                break;
        }
    }

    private static void EmitProgramRoutes(SourceProductionContext ctx, string rootNs)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// API route constants generated by TheWatch.Generators.MauiPageGenerator");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNs}.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>API route constants for all TheWatch programs.</summary>");
        sb.AppendLine("public static class ProgramRoutes");
        sb.AppendLine("{");

        foreach (var p in Programs)
        {
            sb.AppendLine($"    public static class {p.Id}");
            sb.AppendLine("    {");
            sb.AppendLine($"        public const string ServiceName = \"{p.Name}\";");
            sb.AppendLine($"        public const int Port = {p.Port};");
            sb.AppendLine($"        public const string BaseUrl = \"http://localhost:{p.Port}\";");
            sb.AppendLine($"        public const string Health = \"/health\";");
            sb.AppendLine($"        public const string Info = \"/info\";");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");

        ctx.AddSource("ProgramRoutes.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
