using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace TheWatch.Generators;

[Generator]
public class MicroserviceEndpointGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var mappingFiles = context.AdditionalTextsProvider
            .Where(f => f.Path.EndsWith("_mapping.json"));

        var projectName = context.AnalyzerConfigOptionsProvider
            .Select((opts, _) =>
            {
                opts.GlobalOptions.TryGetValue("build_property.RootNamespace", out var ns);
                return ns ?? "TheWatch";
            });

        var combined = mappingFiles.Collect().Combine(projectName);

        context.RegisterSourceOutput(combined, (spc, pair) =>
        {
            var (files, rootNs) = pair;
            if (files.IsEmpty) return;

            // Only emit into service projects, not test projects
            if (rootNs.Contains(".Tests")) return;

            var program = GeneratorHelpers.DetectProgram(rootNs);
            if (program == null) return;

            var text = files[0].GetText()?.ToString();
            if (text == null) return;

            var mapping = JsonDocument.Parse(text).RootElement;
            GenerateEndpoints(spc, mapping, program, rootNs);
        });
    }

    private static void GenerateEndpoints(SourceProductionContext ctx, JsonElement mapping,
        string program, string rootNs)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNs};");
        sb.AppendLine();
        sb.AppendLine("public static class EndpointRegistrations");
        sb.AppendLine("{");
        sb.AppendLine("    public static WebApplication MapAllEndpoints(this WebApplication app)");
        sb.AppendLine("    {");

        int count = 0;

        // Controller matches for this program
        if (mapping.TryGetProperty("controllerMatches", out var ctrlMatches))
        {
            var grouped = ctrlMatches.EnumerateArray()
                .Where(m => m.GetProperty("program").GetString() == program &&
                           m.GetProperty("matchType").GetString() != "unmatched")
                .GroupBy(m => m.GetProperty("controller").GetString() ?? "");

            foreach (var group in grouped)
            {
                sb.AppendLine($"        // {group.Key}");
                foreach (var match in group)
                {
                    var httpMethod = match.GetProperty("httpMethod").GetString()?.ToUpperInvariant() ?? "GET";
                    var path = match.GetProperty("operationPath").GetString() ?? "/";
                    var opId = match.GetProperty("operationId").GetString() ?? "";
                    var methodName = GeneratorHelpers.ExtractOperationName(opId, httpMethod, path);
                    var summary = match.GetProperty("operationSummary").GetString() ?? "";

                    EmitEndpoint(sb, httpMethod, path, methodName, rootNs, summary);
                    count++;
                }
            }
        }

        // Unmatched operations for this program (stubs)
        if (mapping.TryGetProperty("unmatchedOperations", out var unmatchedOps))
        {
            var ops = unmatchedOps.EnumerateArray()
                .Where(o => o.GetProperty("program").GetString() == program)
                .ToList();

            if (ops.Any())
            {
                sb.AppendLine();
                sb.AppendLine("        // --- Stubbed from OpenAPI specs (no existing code) ---");
                foreach (var op in ops)
                {
                    var httpMethod = op.GetProperty("method").GetString()?.ToUpperInvariant() ?? "GET";
                    var path = op.GetProperty("path").GetString() ?? "/";
                    var opId = op.GetProperty("operationId").GetString() ?? "";
                    var methodName = GeneratorHelpers.ExtractOperationName(opId, httpMethod, path);
                    var summary = op.GetProperty("summary").GetString() ?? "";

                    EmitEndpoint(sb, httpMethod, path, methodName, rootNs, summary);
                    count++;
                }
            }
        }

        sb.AppendLine();
        sb.AppendLine("        return app;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource("EndpointRegistrations.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void EmitEndpoint(StringBuilder sb, string httpMethod, string path,
        string methodName, string rootNs, string summary)
    {
        var mapMethod = httpMethod switch
        {
            "GET" => "MapGet",
            "POST" => "MapPost",
            "PUT" => "MapPut",
            "DELETE" => "MapDelete",
            "PATCH" => "MapPatch",
            _ => "MapGet"
        };

        if (!string.IsNullOrEmpty(summary))
        {
            sb.AppendLine($"        // {summary}");
        }

        sb.AppendLine($"        app.{mapMethod}(\"{path}\", ({rootNs}.Services.I{methodName}Service svc) =>");
        sb.AppendLine($"            svc.ExecuteAsync())");
        sb.AppendLine($"            .WithName(\"{methodName}\")");
        sb.AppendLine($"            .WithOpenApi();");
    }
}
