using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace TheWatch.Generators;

[Generator]
public class OpenApiGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var projectInfo = context.AnalyzerConfigOptionsProvider
            .Select((opts, _) =>
            {
                opts.GlobalOptions.TryGetValue("build_property.RootNamespace", out var ns);
                opts.GlobalOptions.TryGetValue("build_property.UseMaui", out var useMaui);
                return (Namespace: ns ?? "TheWatch", UseMaui: useMaui ?? "");
            });

        context.RegisterSourceOutput(projectInfo, (spc, info) =>
        {
            var rootNs = info.Namespace;
            // Skip test projects, the generator itself, MAUI, and non-API projects
            if (rootNs.Contains(".Tests") || rootNs.Contains(".Generators")
                || rootNs.Contains("Dashboard") || rootNs.Contains("Shared")
                || rootNs.Contains("ServiceDefaults") || rootNs.Contains("AppHost"))
                return;
            if (info.UseMaui.Equals("true", System.StringComparison.OrdinalIgnoreCase) ||
                rootNs.Contains(".Mobile"))
                return;

            var program = GeneratorHelpers.DetectProgram(rootNs);
            var serviceName = rootNs;
            var shortName = program != null
                ? ExtractShortName(rootNs, program)
                : rootNs.Split('.').Last();

            EmitOpenApiSetup(spc, rootNs, serviceName, shortName, program);
        });
    }

    private static string ExtractShortName(string rootNs, string program)
    {
        var parts = rootNs.Split('.');
        return parts.Length >= 3 ? parts[parts.Length - 1] : program;
    }

    private static void EmitOpenApiSetup(SourceProductionContext ctx, string rootNs,
        string serviceName, string shortName, string program)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// OpenAPI configuration generated by TheWatch.Generators.OpenApiGenerator");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Scalar.AspNetCore;");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNs};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Auto-generated OpenAPI/Scalar configuration for {serviceName}.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class OpenApiSetup");
        sb.AppendLine("{");

        // ConfigureWatchOpenApi — extension on WebApplicationBuilder
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Adds OpenAPI document generation.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static WebApplicationBuilder ConfigureWatchOpenApi(this WebApplicationBuilder builder)");
        sb.AppendLine("    {");
        sb.AppendLine("        builder.Services.AddOpenApi();");
        sb.AppendLine("        return builder;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // UseWatchOpenApi — extension on WebApplication
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Maps the OpenAPI JSON endpoint and Scalar interactive API docs UI.");
        sb.AppendLine("    /// OpenAPI spec: /openapi/v1.json");
        sb.AppendLine("    /// Scalar UI:    /scalar/v1");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static WebApplication UseWatchOpenApi(this WebApplication app)");
        sb.AppendLine("    {");
        sb.AppendLine("        app.MapOpenApi();");
        sb.AppendLine("        app.MapScalarApiReference(options =>");
        sb.AppendLine("        {");
        sb.AppendLine($"            options.Title = \"{shortName} API\";");
        sb.AppendLine("            options.Theme = ScalarTheme.DeepSpace;");
        sb.AppendLine("        });");
        sb.AppendLine("        return app;");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        ctx.AddSource("OpenApiSetup.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
