using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace TheWatch.Generators;

[Generator]
public class SerilogGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var projectInfo = context.AnalyzerConfigOptionsProvider
            .Select((opts, _) =>
            {
                opts.GlobalOptions.TryGetValue("build_property.RootNamespace", out var ns);
                opts.GlobalOptions.TryGetValue("build_property.UseMaui", out var useMaui);
                return (Namespace: ns ?? "TheWatch", UseMaui: useMaui ?? "");
            });

        context.RegisterSourceOutput(projectInfo, (spc, info) =>
        {
            var rootNs = info.Namespace;
            // Skip test projects, the generator itself, and MAUI projects (no WebApplicationBuilder)
            if (rootNs.Contains(".Tests") || rootNs.Contains(".Generators"))
                return;
            if (info.UseMaui.Equals("true", System.StringComparison.OrdinalIgnoreCase) ||
                rootNs.Contains(".Mobile"))
                return;

            var program = GeneratorHelpers.DetectProgram(rootNs);
            // Also emit for Dashboard and other non-program projects
            var serviceName = rootNs; // e.g. "TheWatch.P2.VoiceEmergency"
            var shortName = program != null
                ? ExtractShortName(rootNs, program)
                : rootNs.Split('.').Last();

            EmitSerilogSetup(spc, rootNs, serviceName, shortName, program);
        });
    }

    private static string ExtractShortName(string rootNs, string program)
    {
        // TheWatch.P2.VoiceEmergency -> VoiceEmergency
        var parts = rootNs.Split('.');
        return parts.Length >= 3 ? parts[parts.Length - 1] : program;
    }

    private static readonly System.Collections.Generic.HashSet<string> SecurityServiceNames =
        new(System.StringComparer.OrdinalIgnoreCase)
        {
            "TheWatch.P5.AuthSecurity",
        };

    private static int GetRetainedFileCount(string serviceName) =>
        SecurityServiceNames.Contains(serviceName) ? 365 : 90;

    private static void EmitSerilogSetup(SourceProductionContext ctx, string rootNs,
        string serviceName, string shortName, string program)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Serilog configuration generated by TheWatch.Generators.SerilogGenerator");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Serilog;");
        sb.AppendLine("using Serilog.Events;");
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.Extensions.Hosting;");
        sb.AppendLine("using TheWatch.Shared.Security;");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNs};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Auto-generated Serilog configuration for {serviceName}.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class SerilogSetup");
        sb.AppendLine("{");
        sb.AppendLine($"    public const string ServiceName = \"{serviceName}\";");
        if (program != null)
            sb.AppendLine($"    public const string Program = \"{program}\";");
        sb.AppendLine();

        // BootstrapSerilog — call before builder.Build()
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Bootstraps Serilog for early startup logging. Call at the top of Program.cs.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    private static int _bootstrapped;");
        sb.AppendLine("    public static void BootstrapSerilog()");
        sb.AppendLine("    {");
        sb.AppendLine("        if (System.Threading.Interlocked.Exchange(ref _bootstrapped, 1) == 1) return;");
        sb.AppendLine("        Log.Logger = CreateLoggerConfiguration().CreateLogger();");
        sb.AppendLine("    }");
        sb.AppendLine();

        // ConfigureWatchSerilog — extension on WebApplicationBuilder
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Configures Serilog on the host with TheWatch standard settings.");
        sb.AppendLine("    /// Console + rolling file sink + optional Seq sink, enriched with service metadata.");
        sb.AppendLine("    /// PII in structured log properties is masked via PiiMaskingEnricher.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static WebApplicationBuilder ConfigureWatchSerilog(this WebApplicationBuilder builder)");
        sb.AppendLine("    {");
        sb.AppendLine("        builder.Host.UseSerilog((context, services, configuration) =>");
        sb.AppendLine("        {");
        sb.AppendLine("            configuration");
        sb.AppendLine("                .ReadFrom.Configuration(context.Configuration)");
        sb.AppendLine("                .MinimumLevel.Information()");
        sb.AppendLine("                .MinimumLevel.Override(\"Microsoft.AspNetCore\", LogEventLevel.Warning)");
        sb.AppendLine("                .MinimumLevel.Override(\"Microsoft.AspNetCore.Hosting\", LogEventLevel.Information)");
        sb.AppendLine("                .MinimumLevel.Override(\"Microsoft.Hosting.Lifetime\", LogEventLevel.Information)");
        sb.AppendLine("                .MinimumLevel.Override(\"Hangfire\", LogEventLevel.Warning)");
        sb.AppendLine("                .Enrich.FromLogContext()");
        sb.AppendLine("                .Enrich.WithMachineName()");
        sb.AppendLine("                .Enrich.WithThreadId()");
        sb.AppendLine($"                .Enrich.WithProperty(\"Service\", \"{serviceName}\")");
        if (program != null)
            sb.AppendLine($"                .Enrich.WithProperty(\"Program\", \"{program}\")");
        // Item 364: PII masking enricher
        sb.AppendLine("                .Enrich.With<PiiMaskingEnricher>()");
        sb.AppendLine("                .WriteTo.Console(");
        sb.AppendLine("                    outputTemplate: \"[{Timestamp:HH:mm:ss} {Level:u3}] [{Service}] {SourceContext}{NewLine}  {Message:lj}{NewLine}{Exception}\")");
        // Item 363: retention — security service uses 365 days, all others use 90 days
        var retainedDays = GetRetainedFileCount(serviceName);
        sb.AppendLine("                .WriteTo.File(");
        sb.AppendLine($"                    path: $\"logs/{shortName}-.log\",");
        sb.AppendLine("                    rollingInterval: RollingInterval.Day,");
        sb.AppendLine($"                    retainedFileCountLimit: {retainedDays},");
        sb.AppendLine("                    outputTemplate: \"{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] [{Service}] {SourceContext} {Message:lj}{NewLine}{Exception}\");");
        // Item 361: optional Seq sink — enabled when Serilog:Seq:ServerUrl is set in configuration
        sb.AppendLine("            var seqUrl = context.Configuration[\"Serilog:Seq:ServerUrl\"];");
        sb.AppendLine("            if (!string.IsNullOrWhiteSpace(seqUrl))");
        sb.AppendLine("            {");
        sb.AppendLine("                var seqApiKey = context.Configuration[\"Serilog:Seq:ApiKey\"];");
        sb.AppendLine("                configuration.WriteTo.Seq(seqUrl,");
        sb.AppendLine("                    apiKey: string.IsNullOrWhiteSpace(seqApiKey) ? null : seqApiKey,");
        sb.AppendLine("                    restrictedToMinimumLevel: LogEventLevel.Information);");
        sb.AppendLine("            }");
        sb.AppendLine("        });");
        sb.AppendLine("        return builder;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // UseWatchSerilogRequestLogging — extension on WebApplication
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Adds Serilog HTTP request logging middleware.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static WebApplication UseWatchSerilogRequestLogging(this WebApplication app)");
        sb.AppendLine("    {");
        sb.AppendLine("        app.UseSerilogRequestLogging(options =>");
        sb.AppendLine("        {");
        sb.AppendLine("            options.MessageTemplate = \"{RequestMethod} {RequestPath} responded {StatusCode} in {Elapsed:0.000}ms\";");
        sb.AppendLine("            options.EnrichDiagnosticContext = (diagnosticContext, httpContext) =>");
        sb.AppendLine("            {");
        sb.AppendLine("                diagnosticContext.Set(\"RequestHost\", httpContext.Request.Host.Value ?? \"\");");
        sb.AppendLine("                diagnosticContext.Set(\"UserAgent\", httpContext.Request.Headers[\"User-Agent\"].FirstOrDefault() ?? \"\");");
        sb.AppendLine("            };");
        sb.AppendLine("        });");
        sb.AppendLine("        return app;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Private helper
        sb.AppendLine("    private static LoggerConfiguration CreateLoggerConfiguration()");
        sb.AppendLine("    {");
        sb.AppendLine("        return new LoggerConfiguration()");
        sb.AppendLine("            .MinimumLevel.Information()");
        sb.AppendLine("            .MinimumLevel.Override(\"Microsoft.AspNetCore\", LogEventLevel.Warning)");
        sb.AppendLine("            .Enrich.FromLogContext()");
        sb.AppendLine("            .Enrich.WithMachineName()");
        sb.AppendLine("            .Enrich.WithThreadId()");
        sb.AppendLine($"            .Enrich.WithProperty(\"Service\", \"{serviceName}\")");
        // Item 364: PII masking enricher
        sb.AppendLine("            .Enrich.With<PiiMaskingEnricher>()");
        sb.AppendLine("            .WriteTo.Console(");
        sb.AppendLine("                outputTemplate: \"[{Timestamp:HH:mm:ss} {Level:u3}] [{Service}] {SourceContext}{NewLine}  {Message:lj}{NewLine}{Exception}\")");
        // Item 363: retention — security service uses 365 days, all others use 90 days
        sb.AppendLine("            .WriteTo.File(");
        sb.AppendLine($"                path: $\"logs/{shortName}-.log\",");
        sb.AppendLine("                rollingInterval: RollingInterval.Day,");
        sb.AppendLine($"                retainedFileCountLimit: {retainedDays});");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        ctx.AddSource("SerilogSetup.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
