using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace TheWatch.Generators;

[Generator]
public class XMLGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var projectInfo = context.AnalyzerConfigOptionsProvider
            .Select((opts, _) =>
            {
                opts.GlobalOptions.TryGetValue("build_property.RootNamespace", out var ns);
                opts.GlobalOptions.TryGetValue("build_property.UseMaui", out var useMaui);
                return (Namespace: ns ?? "TheWatch", UseMaui: useMaui ?? "");
            });

        context.RegisterSourceOutput(projectInfo, (spc, info) =>
        {
            var rootNs = info.Namespace;
            // Skip test projects, the generator itself, and non-service projects
            if (rootNs.Contains(".Tests") || rootNs.Contains(".Generators")
                || rootNs.Contains("ServiceDefaults") || rootNs.Contains("AppHost"))
                return;
            if (info.UseMaui.Equals("true", System.StringComparison.OrdinalIgnoreCase) ||
                rootNs.Contains(".Mobile"))
                return;

            var serviceName = rootNs;
            EmitXmlDocSetup(spc, rootNs, serviceName);
        });
    }

    private static void EmitXmlDocSetup(SourceProductionContext ctx, string rootNs,
        string serviceName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// XML documentation setup generated by TheWatch.Generators.XMLGenerator");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.IO;");
        sb.AppendLine("using System.Reflection;");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNs};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Auto-generated XML documentation helpers for {serviceName}.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class XmlDocSetup");
        sb.AppendLine("{");

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets the file name of the XML documentation file for this assembly.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public const string XmlDocFileName = \"{rootNs}.xml\";");
        sb.AppendLine();

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets the full path to the XML documentation file for this assembly.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static string XmlDocPath =>");
        sb.AppendLine("        Path.Combine(AppContext.BaseDirectory, XmlDocFileName);");
        sb.AppendLine();

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Returns <c>true</c> if the XML documentation file exists on disk.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static bool XmlDocExists => File.Exists(XmlDocPath);");

        sb.AppendLine("}");

        ctx.AddSource("XmlDocSetup.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
