// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TheWatch.Geospatial;

#nullable disable

namespace TheWatch.Geospatial.Data.Migrations
{
    [DbContext(typeof(GeospatialDbContext))]
    [Migration("20260226142708_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TheWatch.Geospatial.Spatial.DisasterZone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<MultiPolygon>("AffectedArea")
                        .IsRequired()
                        .HasColumnType("geometry (MultiPolygon, 4326)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DisasterEventId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisasterType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Point>("Epicenter")
                        .IsRequired()
                        .HasColumnType("geometry (Point, 4326)");

                    b.Property<double>("EstimatedAffectedPopulation")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AffectedArea");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("AffectedArea"), "gist");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DisasterEventId");

                    b.HasIndex("Epicenter");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Epicenter"), "gist");

                    b.HasIndex("ResolvedAt");

                    b.HasIndex("Severity");

                    b.ToTable("DisasterZones");
                });

            modelBuilder.Entity("TheWatch.Geospatial.Spatial.DispatchRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Point>("Destination")
                        .IsRequired()
                        .HasColumnType("geometry (Point, 4326)");

                    b.Property<double>("DistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<double>("EstimatedMinutes")
                        .HasColumnType("double precision");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<Point>("Origin")
                        .IsRequired()
                        .HasColumnType("geometry (Point, 4326)");

                    b.Property<Guid>("ResponderId")
                        .HasColumnType("uuid");

                    b.Property<LineString>("RoutePath")
                        .IsRequired()
                        .HasColumnType("geometry (LineString, 4326)");

                    b.Property<string>("RouteStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Destination");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Destination"), "gist");

                    b.HasIndex("IncidentId");

                    b.HasIndex("Origin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Origin"), "gist");

                    b.HasIndex("ResponderId");

                    b.HasIndex("RoutePath");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("RoutePath"), "gist");

                    b.HasIndex("RouteStatus");

                    b.ToTable("DispatchRoutes");
                });

            modelBuilder.Entity("TheWatch.Geospatial.Spatial.EvacuationRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("CapacityPersons")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DisasterZoneId")
                        .HasColumnType("uuid");

                    b.Property<double>("DistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<Point>("EndPoint")
                        .IsRequired()
                        .HasColumnType("geometry (Point, 4326)");

                    b.Property<double>("EstimatedMinutes")
                        .HasColumnType("double precision");

                    b.Property<LineString>("Path")
                        .IsRequired()
                        .HasColumnType("geometry (LineString, 4326)");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RouteStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Point>("StartPoint")
                        .IsRequired()
                        .HasColumnType("geometry (Point, 4326)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DisasterZoneId");

                    b.HasIndex("EndPoint");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("EndPoint"), "gist");

                    b.HasIndex("Path");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Path"), "gist");

                    b.HasIndex("RouteStatus");

                    b.HasIndex("StartPoint");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("StartPoint"), "gist");

                    b.ToTable("EvacuationRoutes");
                });

            modelBuilder.Entity("TheWatch.Geospatial.Spatial.FamilyGeofence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Polygon>("Boundary")
                        .IsRequired()
                        .HasColumnType("geometry (Polygon, 4326)");

                    b.Property<Point>("Center")
                        .IsRequired()
                        .HasColumnType("geometry (Point, 4326)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FamilyGroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("RadiusMeters")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AlertType");

                    b.HasIndex("Boundary");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Boundary"), "gist");

                    b.HasIndex("Center");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Center"), "gist");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FamilyGroupId");

                    b.ToTable("FamilyGeofences");
                });

            modelBuilder.Entity("TheWatch.Geospatial.Spatial.FamilyMemberLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<double>("Accuracy")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("ActiveGeofenceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FamilyGroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsInsideGeofence")
                        .HasColumnType("boolean");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry (Point, 4326)");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActiveGeofenceId");

                    b.HasIndex("FamilyGroupId");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("MemberId");

                    b.HasIndex("RecordedAt");

                    b.ToTable("FamilyMemberLocations");
                });

            modelBuilder.Entity("TheWatch.Geospatial.Spatial.GeoFence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Polygon>("Boundary")
                        .IsRequired()
                        .HasColumnType("geometry (Polygon, 4326)");

                    b.Property<Point>("Center")
                        .IsRequired()
                        .HasColumnType("geometry (Point, 4326)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FenceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("OwnerEntityType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double>("RadiusMeters")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Boundary");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Boundary"), "gist");

                    b.HasIndex("Center");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Center"), "gist");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FenceType");

                    b.HasIndex("OwnerEntityId");

                    b.ToTable("GeoFences");
                });

            modelBuilder.Entity("TheWatch.Geospatial.Spatial.GeoLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<double>("Accuracy")
                        .HasColumnType("double precision");

                    b.Property<double>("Altitude")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry (Point, 4326)");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("LocationType");

                    b.HasIndex("RecordedAt");

                    b.ToTable("GeoLocations");
                });

            modelBuilder.Entity("TheWatch.Geospatial.Spatial.GeoZone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Polygon>("Boundary")
                        .IsRequired()
                        .HasColumnType("geometry (Polygon, 4326)");

                    b.Property<Point>("Centroid")
                        .IsRequired()
                        .HasColumnType("geometry (Point, 4326)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentZoneId")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ZoneType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Boundary");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Boundary"), "gist");

                    b.HasIndex("Centroid");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Centroid"), "gist");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("ParentZoneId");

                    b.HasIndex("Severity");

                    b.HasIndex("ZoneType");

                    b.ToTable("GeoZones");
                });

            modelBuilder.Entity("TheWatch.Geospatial.Spatial.GeofenceEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("FamilyGeofenceId")
                        .HasColumnType("uuid");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry (Point, 4326)");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("FamilyGeofenceId");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("MemberId");

                    b.HasIndex("OccurredAt");

                    b.ToTable("GeofenceEvents");
                });

            modelBuilder.Entity("TheWatch.Geospatial.Spatial.IncidentZone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("CurrentRadiusMeters")
                        .HasColumnType("double precision");

                    b.Property<Point>("EpicenterLocation")
                        .IsRequired()
                        .HasColumnType("geometry (Point, 4326)");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double>("InitialRadiusMeters")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Polygon>("PerimeterBoundary")
                        .IsRequired()
                        .HasColumnType("geometry (Polygon, 4326)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EpicenterLocation");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("EpicenterLocation"), "gist");

                    b.HasIndex("IncidentId");

                    b.HasIndex("PerimeterBoundary");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("PerimeterBoundary"), "gist");

                    b.HasIndex("ResolvedAt");

                    b.HasIndex("Severity");

                    b.ToTable("IncidentZones");
                });

            modelBuilder.Entity("TheWatch.Geospatial.Spatial.LocationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<double>("Accuracy")
                        .HasColumnType("double precision");

                    b.Property<double>("Heading")
                        .HasColumnType("double precision");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry (Point, 4326)");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Speed")
                        .HasColumnType("double precision");

                    b.Property<Guid>("TrackedEntityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("RecordedAt");

                    b.HasIndex("TrackedEntityId");

                    b.ToTable("LocationHistories");
                });

            modelBuilder.Entity("TheWatch.Geospatial.Spatial.PointOfInterest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEmergencyFacility")
                        .HasColumnType("boolean");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry (Point, 4326)");

                    b.Property<Dictionary<string, string>>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.ToTable("PointOfInterests");
                });

            modelBuilder.Entity("TheWatch.Geospatial.Spatial.ResponderPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DispatchStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double?>("DistanceToIncidentMeters")
                        .HasColumnType("double precision");

                    b.Property<double?>("EtaMinutes")
                        .HasColumnType("double precision");

                    b.Property<double>("Heading")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry (Point, 4326)");

                    b.Property<DateTimeOffset>("ReportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ResponderId")
                        .HasColumnType("uuid");

                    b.Property<double>("Speed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("DispatchStatus");

                    b.HasIndex("IncidentId");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("ReportedAt");

                    b.HasIndex("ResponderId");

                    b.ToTable("ResponderPositions");
                });

            modelBuilder.Entity("TheWatch.Geospatial.Spatial.ShelterLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentOccupancy")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DisasterZoneId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasMedical")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasPower")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasWater")
                        .HasColumnType("boolean");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry (Point, 4326)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DisasterZoneId");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("Status");

                    b.ToTable("ShelterLocations");
                });

            modelBuilder.Entity("TheWatch.Geospatial.Spatial.SpatialSearchResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<double>("DistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("FoundAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry (Point, 4326)");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("FoundAt");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.ToTable("SpatialSearchResults");
                });

            modelBuilder.Entity("TheWatch.Geospatial.Spatial.TrackedEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ExternalEntityId")
                        .HasColumnType("uuid");

                    b.Property<double>("LastHeading")
                        .HasColumnType("double precision");

                    b.Property<Point>("LastKnownLocation")
                        .IsRequired()
                        .HasColumnType("geometry (Point, 4326)");

                    b.Property<double>("LastSpeed")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ExternalEntityId");

                    b.HasIndex("LastKnownLocation");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("LastKnownLocation"), "gist");

                    b.HasIndex("LastUpdatedAt");

                    b.HasIndex("Status");

                    b.ToTable("TrackedEntities");
                });

            modelBuilder.Entity("TheWatch.Geospatial.Spatial.TrackingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<LineString>("Path")
                        .IsRequired()
                        .HasColumnType("geometry (LineString, 4326)");

                    b.Property<string>("SessionStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("TotalDistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<Guid>("TrackedEntityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EndedAt");

                    b.HasIndex("Path");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Path"), "gist");

                    b.HasIndex("SessionStatus");

                    b.HasIndex("StartedAt");

                    b.HasIndex("TrackedEntityId");

                    b.ToTable("TrackingSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
